-- ============================================================
-- AREWARIN UNIFIED V17 — CONTROL + AUTOMATION UPGRADE
-- Existing V16 project upgrade
-- Manager Action Center / Student 360 / Search / Audit / Roles / Health
-- Group Broadcast / Tutor Pipeline / Soft Archive / Student V17 bootstrap
-- ============================================================
begin;
create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- 1) Audit log
-- ------------------------------------------------------------
create table if not exists public.aw_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_role text,
  action text not null,
  table_name text not null,
  record_id text,
  before_data jsonb,
  after_data jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists aw_audit_log_created_idx on public.aw_audit_log(created_at desc);
create index if not exists aw_audit_log_record_idx on public.aw_audit_log(table_name,record_id,created_at desc);

create or replace function public.aw_v17_audit_trigger()
returns trigger language plpgsql security definer set search_path=public as $$
declare rid text; role_name text;
begin
  begin select role into role_name from public.profiles where id=auth.uid(); exception when others then role_name:=null; end;
  if tg_op='DELETE' then rid:=coalesce(to_jsonb(old)->>'id',''); else rid:=coalesce(to_jsonb(new)->>'id',''); end if;
  insert into public.aw_audit_log(actor_user_id,actor_role,action,table_name,record_id,before_data,after_data)
  values(auth.uid(),coalesce(role_name,case when auth.uid() is null then 'system' else 'authenticated' end),lower(tg_op),tg_table_name,rid,
    case when tg_op in('UPDATE','DELETE') then to_jsonb(old) else null end,
    case when tg_op in('INSERT','UPDATE') then to_jsonb(new) else null end);
  return coalesce(new,old);
end $$;

do $$declare t text;begin
  foreach t in array array[
    'payments','enrollments','os_student_course_enrollments','os_hour_ledger','courses','tutors',
    'student_support_tickets','student_reschedule_requests','student_assignment_submissions','tutor_applications'
  ] loop
    if to_regclass('public.'||t) is not null then
      execute format('drop trigger if exists trg_aw_v17_audit on public.%I',t);
      execute format('create trigger trg_aw_v17_audit after insert or update or delete on public.%I for each row execute function public.aw_v17_audit_trigger()',t);
    end if;
  end loop;
end$$;

alter table public.aw_audit_log enable row level security;
drop policy if exists aw_v17_audit_manager_read on public.aw_audit_log;
create policy aw_v17_audit_manager_read on public.aw_audit_log for select to authenticated using(public.is_manager());
revoke all on public.aw_audit_log from anon;
grant select on public.aw_audit_log to authenticated;

-- ------------------------------------------------------------
-- 2) Role / permission matrix (future-ready; admin/manager work immediately)
-- ------------------------------------------------------------
create table if not exists public.aw_role_permissions (
  role_key text not null,
  module_key text not null,
  can_view boolean not null default true,
  can_create boolean not null default false,
  can_update boolean not null default false,
  can_delete boolean not null default false,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  primary key(role_key,module_key)
);
insert into public.aw_role_permissions(role_key,module_key,can_view,can_create,can_update,can_delete) values
('admin','*',true,true,true,true),
('manager','*',true,true,true,true),
('finance','finance',true,true,true,false),
('finance','students',true,false,false,false),
('academic','students',true,true,true,false),
('academic','teaching',true,true,true,false),
('academic','homework',true,true,true,false),
('support','students',true,false,false,false),
('support','support',true,true,true,false),
('tutor_coordinator','tutors',true,true,true,false),
('tutor_coordinator','teaching',true,true,true,false)
on conflict(role_key,module_key) do nothing;
alter table public.aw_role_permissions enable row level security;
drop policy if exists aw_v17_permissions_manager on public.aw_role_permissions;
create policy aw_v17_permissions_manager on public.aw_role_permissions for all to authenticated using(public.is_manager()) with check(public.is_manager());
grant select,insert,update,delete on public.aw_role_permissions to authenticated;

create or replace function public.aw_v17_can(p_module text,p_action text default 'view')
returns boolean language plpgsql stable security definer set search_path=public as $$
declare r text; x public.aw_role_permissions;
begin
  select role into r from public.profiles where id=auth.uid();
  if r in('admin','manager') then return true; end if;
  select * into x from public.aw_role_permissions where role_key=r and module_key=p_module;
  if x.role_key is null then select * into x from public.aw_role_permissions where role_key=r and module_key='*'; end if;
  if x.role_key is null then return false; end if;
  return case p_action when 'create' then x.can_create when 'update' then x.can_update when 'delete' then x.can_delete else x.can_view end;
end$$;
grant execute on function public.aw_v17_can(text,text) to authenticated;

-- ------------------------------------------------------------
-- 3) Soft archive columns
-- ------------------------------------------------------------
alter table public.os_students add column if not exists archived_at timestamptz;
alter table public.os_students add column if not exists deleted_at timestamptz;
alter table public.courses add column if not exists archived_at timestamptz;
alter table public.courses add column if not exists deleted_at timestamptz;
alter table public.tutors add column if not exists archived_at timestamptz;
alter table public.tutors add column if not exists deleted_at timestamptz;
alter table public.enrollments add column if not exists archived_at timestamptz;
alter table public.enrollments add column if not exists deleted_at timestamptz;

-- ------------------------------------------------------------
-- 4) Tutor recruitment pipeline
-- ------------------------------------------------------------
alter table public.tutor_applications add column if not exists pipeline_stage text;
update public.tutor_applications set pipeline_stage=case
  when status='new' then 'new'
  when status='reviewing' then 'review'
  when status='interview' then 'interview'
  when status='accepted' then 'accepted'
  when status in('rejected','withdrawn') then status
  else 'new' end
where pipeline_stage is null;
alter table public.tutor_applications alter column pipeline_stage set default 'new';

-- ------------------------------------------------------------
-- 5) Group broadcasts
-- ------------------------------------------------------------
create table if not exists public.os_group_broadcasts (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.os_student_groups(id) on delete cascade,
  title text not null,
  body text not null,
  visible_to_students boolean not null default true,
  visible_to_parents boolean not null default true,
  pinned boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);
create index if not exists os_group_broadcasts_group_idx on public.os_group_broadcasts(group_id,created_at desc);
alter table public.os_group_broadcasts enable row level security;
drop policy if exists aw_v17_group_broadcast_staff on public.os_group_broadcasts;
create policy aw_v17_group_broadcast_staff on public.os_group_broadcasts for all to authenticated using(public.os_is_staff() or public.is_manager()) with check(public.os_is_staff() or public.is_manager());
drop policy if exists aw_v17_group_broadcast_student on public.os_group_broadcasts;
create policy aw_v17_group_broadcast_student on public.os_group_broadcasts for select to authenticated using(
  visible_to_students=true and group_id in(select group_id from public.os_student_group_members where student_id=public.aw_my_student_id() and is_active=true)
);
grant select,insert,update,delete on public.os_group_broadcasts to authenticated;

-- ------------------------------------------------------------
-- 6) Action Center
-- ------------------------------------------------------------
create or replace function public.aw_v17_action_center()
returns jsonb language plpgsql security definer set search_path=public as $$
declare result jsonb;
begin
  if not public.is_manager() then raise exception 'Not authorized'; end if;
  select jsonb_build_object(
    'pending_payments',(select count(*) from public.payments where status='pending'),
    'pending_reschedules',(select count(*) from public.student_reschedule_requests where status='pending'),
    'homework_to_grade',(select count(*) from public.student_assignment_submissions where status='submitted'),
    'open_tickets',(select count(*) from public.student_support_tickets where status in('open','in_progress','waiting_student')),
    'urgent_tickets',(select count(*) from public.student_support_tickets where status not in('resolved','closed') and priority='urgent'),
    'low_hours',(select count(*) from public.os_hour_pools where status='active' and unlimited=false and total_hours is not null and greatest(0,total_hours-used_hours)<=3),
    'new_tutor_apps',(select count(*) from public.tutor_applications where coalesce(pipeline_stage,status) in('new','review')),
    'today_sessions',(select count(*) from public.student_schedule_events where start_at::date=(now() at time zone 'Asia/Bangkok')::date and status in('scheduled','rescheduled')),
    'overdue_installments',(select count(*) from public.portal_payment_installments where status in('pending','partial','overdue') and due_date<current_date),
    'active_students',(select count(*) from public.os_students where archived=false and status='active')
  ) into result;
  return result;
end$$;
grant execute on function public.aw_v17_action_center() to authenticated;

-- ------------------------------------------------------------
-- 7) Universal Search
-- ------------------------------------------------------------
create or replace function public.aw_v17_search(p_query text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare q text:=trim(coalesce(p_query,'')); result jsonb;
begin
  if not public.is_manager() then raise exception 'Not authorized'; end if;
  if length(q)<2 then return '[]'::jsonb; end if;
  with results as (
    select 'student'::text kind,s.id::text id,coalesce(s.display_name,s.first_name||' '||s.last_name) title,
      concat_ws(' · ',s.student_code,s.phone,s.school) subtitle,'student360' route,100 score
    from public.os_students s where s.deleted_at is null and (s.display_name ilike '%'||q||'%' or s.first_name ilike '%'||q||'%' or s.last_name ilike '%'||q||'%' or s.phone ilike '%'||q||'%' or s.student_code ilike '%'||q||'%')
    union all
    select 'enrollment',e.id::text,coalesce(e.fullname,e.nickname,'Enrollment'),concat_ws(' · ',e.phone,e.receipt_no,e.course_text),'enrollments',90
    from public.enrollments e where e.deleted_at is null and (e.fullname ilike '%'||q||'%' or e.nickname ilike '%'||q||'%' or e.phone ilike '%'||q||'%' or e.receipt_no ilike '%'||q||'%' or e.course_text ilike '%'||q||'%')
    union all
    select 'course',c.id::text,c.name,coalesce(c.short_detail,''),'courses',80 from public.courses c where c.deleted_at is null and (c.name ilike '%'||q||'%' or c.short_detail ilike '%'||q||'%')
    union all
    select 'tutor',t.id::text,t.display_name,coalesce(t.full_name||' · ','')||coalesce(t.role_text,''),'tutors',80 from public.tutors t where t.deleted_at is null and (t.display_name ilike '%'||q||'%' or t.full_name ilike '%'||q||'%')
    union all
    select 'ticket',st.id::text,coalesce(st.ticket_no,'Ticket')||' · '||st.subject,st.category||' · '||st.status,'v17control',75 from public.student_support_tickets st where st.subject ilike '%'||q||'%' or st.description ilike '%'||q||'%' or st.ticket_no ilike '%'||q||'%'
  ), limited as (select * from results order by score desc,title limit 30)
  select coalesce(jsonb_agg(to_jsonb(r) order by score desc,title),'[]'::jsonb) into result from limited r;
  return result;
end$$;
grant execute on function public.aw_v17_search(text) to authenticated;

-- ------------------------------------------------------------
-- 8) Student 360
-- ------------------------------------------------------------
create or replace function public.aw_v17_student_360(p_student_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare result jsonb;
begin
  if not public.is_manager() then raise exception 'Not authorized'; end if;
  if not exists(select 1 from public.os_students where id=p_student_id) then raise exception 'Student not found'; end if;
  select jsonb_build_object(
    'student',(select to_jsonb(s) from public.os_students s where s.id=p_student_id),
    'courses',coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at desc) from public.os_student_course_enrollments x where x.student_id=p_student_id),'[]'::jsonb),
    'hour_pools',coalesce((select jsonb_agg(to_jsonb(x) order by x.updated_at desc) from public.os_hour_pools x where x.student_id=p_student_id),'[]'::jsonb),
    'hour_ledger',coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at desc) from (select * from public.os_hour_ledger where student_id=p_student_id order by created_at desc limit 100)x),'[]'::jsonb),
    'attendance',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'status',a.status,'note',a.note,'deducted_hours',coalesce(a.deducted_hours,0),'session_date',s.session_date,'title',s.title,'course_id',s.course_id) order by s.session_date desc) from public.os_student_attendance a join public.os_attendance_sessions s on s.id=a.session_id where a.student_id=p_student_id),'[]'::jsonb),
    'payments',coalesce((select jsonb_agg(to_jsonb(p) order by p.created_at desc) from public.payments p where p.enrollment_id in(select source_enrollment_id from public.os_student_course_enrollments where student_id=p_student_id and source_enrollment_id is not null)),'[]'::jsonb),
    'schedule',coalesce((select jsonb_agg(to_jsonb(e) order by e.start_at desc) from public.student_schedule_events e where e.student_id=p_student_id or e.group_id in(select group_id from public.os_student_group_members where student_id=p_student_id and is_active=true)),'[]'::jsonb),
    'assignments',coalesce((select jsonb_agg(to_jsonb(a) order by coalesce(a.due_at,'2999-01-01'::timestamptz)) from public.student_assignments a where a.student_id=p_student_id or a.course_id in(select course_id from public.os_student_course_enrollments where student_id=p_student_id) or a.group_id in(select group_id from public.os_student_group_members where student_id=p_student_id and is_active=true)),'[]'::jsonb),
    'submissions',coalesce((select jsonb_agg(to_jsonb(x) order by x.submitted_at desc) from public.student_assignment_submissions x where x.student_id=p_student_id),'[]'::jsonb),
    'tickets',coalesce((select jsonb_agg(to_jsonb(x) order by x.updated_at desc) from public.student_support_tickets x where x.student_id=p_student_id),'[]'::jsonb),
    'parent_links',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'parent_name',x.parent_name,'relationship',x.relationship,'active',x.active,'last_used_at',x.last_used_at,'created_at',x.created_at) order by x.created_at desc) from public.student_parent_links x where x.student_id=p_student_id),'[]'::jsonb),
    'certificates',coalesce((select jsonb_agg(to_jsonb(x) order by x.issued_at desc) from public.student_certificates x where x.student_id=p_student_id),'[]'::jsonb),
    'groups',coalesce((select jsonb_agg(jsonb_build_object('id',g.id,'group_code',g.group_code,'name',g.name,'status',g.status,'course_id',g.course_id,'tutor_id',g.tutor_id)) from public.os_student_group_members gm join public.os_student_groups g on g.id=gm.group_id where gm.student_id=p_student_id and gm.is_active=true),'[]'::jsonb)
  ) into result;
  return result;
end$$;
grant execute on function public.aw_v17_student_360(uuid) to authenticated;

-- ------------------------------------------------------------
-- 9) System Health / integrity
-- ------------------------------------------------------------
create or replace function public.aw_v17_system_health()
returns jsonb language plpgsql security definer set search_path=public as $$
declare issues jsonb; summary jsonb;
begin
  if not public.is_manager() then raise exception 'Not authorized'; end if;
  with i as (
    select 'active_course_payment_mismatch' code,'สูง' severity,'คอร์ส Active แต่ Payment ยังไม่ paid' title,count(*)::int total
    from public.os_student_course_enrollments sce join public.payments p on p.enrollment_id=sce.source_enrollment_id where sce.status in('active','paused','completed') and p.status<>'paid'
    union all
    select 'active_course_enrollment_mismatch','สูง','คอร์ส Active แต่ Enrollment ยังไม่ confirmed',count(*)::int from public.os_student_course_enrollments sce join public.enrollments e on e.id=sce.source_enrollment_id where sce.status in('active','paused','completed') and e.status<>'confirmed'
    union all
    select 'course_without_hour_pool','กลาง','คอร์ส Active ไม่มี Hour Pool',count(*)::int from public.os_student_course_enrollments where status='active' and hour_pool_id is null
    union all
    select 'group_without_members','ต่ำ','Group Locker Active แต่ไม่มีสมาชิก',count(*)::int from public.os_student_groups g where g.status='active' and not exists(select 1 from public.os_student_group_members gm where gm.group_id=g.id and gm.is_active=true)
    union all
    select 'pending_payment_old','กลาง','Payment pending เกิน 3 วัน',count(*)::int from public.payments where status='pending' and created_at<now()-interval '3 days'
    union all
    select 'urgent_ticket','สูง','Support Ticket เร่งด่วนยังไม่ปิด',count(*)::int from public.student_support_tickets where priority='urgent' and status not in('resolved','closed')
  ) select coalesce(jsonb_agg(to_jsonb(i)),'[]'::jsonb),jsonb_build_object('issue_total',coalesce(sum(total),0),'checked_at',now()) into issues,summary from i;
  return jsonb_build_object('summary',summary,'issues',issues);
end$$;
grant execute on function public.aw_v17_system_health() to authenticated;

-- ------------------------------------------------------------
-- 10) Finance aging
-- ------------------------------------------------------------
create or replace function public.aw_v17_finance_aging()
returns jsonb language sql stable security definer set search_path=public as $$
  select case when public.is_manager() then jsonb_build_object(
    'current',coalesce(sum(amount_submitted) filter(where status='pending' and created_at>=now()-interval '7 days'),0),
    'd8_30',coalesce(sum(amount_submitted) filter(where status='pending' and created_at<now()-interval '7 days' and created_at>=now()-interval '30 days'),0),
    'over30',coalesce(sum(amount_submitted) filter(where status='pending' and created_at<now()-interval '30 days'),0),
    'pending_count',count(*) filter(where status='pending'),
    'paid_30d',coalesce(sum(coalesce(verified_amount,amount_submitted)) filter(where status='paid' and coalesce(verified_at,created_at)>=now()-interval '30 days'),0)
  ) else jsonb_build_object('error','not_authorized') end from public.payments;
$$;
grant execute on function public.aw_v17_finance_aging() to authenticated;

-- ------------------------------------------------------------
-- 11) V17 Student bootstrap: V16 + group broadcasts
-- ------------------------------------------------------------
create or replace function public.student_v17_bootstrap()
returns jsonb language plpgsql security definer set search_path=public as $$
declare sid uuid:=public.aw_my_student_id(); base jsonb;
begin
  if sid is null then raise exception 'Student account is not linked'; end if;
  base:=public.student_v16_bootstrap();
  return base||jsonb_build_object(
    'v17_group_broadcasts',coalesce((select jsonb_agg(jsonb_build_object('id',b.id,'group_id',b.group_id,'group_name',g.name,'title',b.title,'body',b.body,'pinned',b.pinned,'created_at',b.created_at,'expires_at',b.expires_at) order by b.pinned desc,b.created_at desc) from public.os_group_broadcasts b join public.os_student_groups g on g.id=b.group_id where b.visible_to_students=true and (b.expires_at is null or b.expires_at>now()) and b.group_id in(select group_id from public.os_student_group_members where student_id=sid and is_active=true)),'[]'::jsonb)
  );
end$$;
grant execute on function public.student_v17_bootstrap() to authenticated;

commit;

select 'V17_READY' as status,
  (select count(*) from public.aw_role_permissions) permission_rows,
  (select count(*) from public.os_group_broadcasts) broadcasts,
  (select count(*) from public.aw_audit_log) audit_rows;
