(() => {
  'use strict';

  const cfg = window.AREWARIN_CONFIG || {};
  const $ = id => document.getElementById(id);
  const $$ = (sel, root=document) => [...root.querySelectorAll(sel)];
  const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const num = v => Number(v || 0);
  const money = v => new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:0}).format(num(v));
  const date = v => v ? new Intl.DateTimeFormat('th-TH',{dateStyle:'medium'}).format(new Date(String(v).length===10?`${v}T00:00:00`:v)) : '—';
  const dateTime = v => v ? new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)) : '—';
  const today = () => new Date().toISOString().slice(0,10);
  const slugPhone = v => String(v||'').replace(/[^0-9+]/g,'');

  if (!cfg.SUPABASE_URL || !cfg.SUPABASE_ANON_KEY || !window.supabase) {
    document.body.innerHTML = '<div style="font-family:Prompt,sans-serif;padding:40px"><h2>ไม่พบ Supabase configuration</h2><p>ตรวจสอบ ../config.js</p></div>';
    return;
  }

  const sb = window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY, {
    auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}
  });

  const state = {
    session:null, staff:null, role:'teacher', section:'overview', subtab:{students:'students',courses:'courses',teaching:'attendance',team:'tutors',settings:'health'},
    systemReady:true, errors:[], loading:false,
    tutors:[], courses:[], enrollments:[], payments:[], tutorApplications:[], speakers:[], schedules:[], scheduleTemplates:[], promotions:[], prices:[],
    students:[], studentCourses:[], crm:[], attendanceSessions:[], attendance:[], teachingLogs:[], learningTopics:[], learningAssets:[], learningAssignments:[], tasks:[], announcements:[], financeEntries:[], paymentSlips:[], library:[], hr:[], courseRequests:[], quickReplies:[], osSettings:[], staffProfiles:[]
  };

  function toast(message, type='success') {
    const el = document.createElement('div');
    el.className = `toast ${type}`;
    el.textContent = message;
    document.body.appendChild(el);
    setTimeout(()=>el.remove(),3200);
  }
  function errorText(e){ return String(e?.message || e || 'Unknown error'); }
  function swalError(title,e){ return Swal.fire({icon:'error',title,text:errorText(e),confirmButtonColor:'#0ea5e9',customClass:{popup:'rounded-3xl'}}); }
  function isAdmin(){ return state.role === 'admin'; }
  function tutor(id){ return state.tutors.find(x=>x.id===id); }
  function course(id){ return state.courses.find(x=>x.id===id); }
  function student(id){ return state.students.find(x=>x.id===id); }
  function studentCourseRows(id){ return state.studentCourses.filter(x=>x.student_id===id); }
  function initials(name){ return String(name||'AW').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase() || 'AW'; }
  function studentStatusClass(s){ return s==='active'?'green':s==='pending'?'amber':s==='archived'||s==='inactive'?'red':'blue'; }
  function paymentStatusClass(s){ return s==='paid'?'green':s==='pending'?'amber':s==='rejected'?'red':'blue'; }

  async function ensureStaff(session){
    if(!session?.user) return null;
    let {data,error} = await sb.from('os_staff_profiles').select('user_id,display_name,role,is_active').eq('user_id',session.user.id).maybeSingle();
    if(!error && data?.is_active && ['teacher','admin'].includes(data.role)) return data;
    // Fallback keeps the subweb reachable immediately for an existing Manager/Admin.
    const fallback = await sb.from('profiles').select('display_name,role').eq('id',session.user.id).maybeSingle();
    if(!fallback.error && fallback.data && ['manager','admin'].includes(fallback.data.role)) {
      state.systemReady = false;
      state.errors.push('ยังไม่ได้รัน TUTOR_OS_V14_UPGRADE.sql — ใช้งานได้เฉพาะข้อมูลระบบหลักจนกว่าจะอัปเกรดฐานข้อมูล');
      return {user_id:session.user.id,display_name:fallback.data.display_name||session.user.email,role:'admin',is_active:true,fallback:true};
    }
    return null;
  }

  async function boot(){
    const {data:{session}} = await sb.auth.getSession();
    if(session){
      const profile = await ensureStaff(session);
      if(profile) return enterApp(session,profile);
      await sb.auth.signOut();
    }
    showLogin();
  }

  function showLogin(){ $('loginView').classList.remove('hidden'); $('appView').classList.add('hidden'); }
  async function enterApp(session,staff){
    state.session=session; state.staff=staff; state.role=staff.role;
    $('loginView').classList.add('hidden'); $('appView').classList.remove('hidden');
    $('userLabel').textContent = `${staff.display_name || session.user.email} • ${staff.role}`;
    $$('.admin-only').forEach(x=>x.classList.toggle('hidden',!isAdmin()));
    if(!isAdmin() && state.section==='finance') state.section='overview';
    await loadAll();
    routeFromUrl();
  }

  $('loginForm').addEventListener('submit', async e=>{
    e.preventDefault();
    const btn=e.currentTarget.querySelector('button'); btn.disabled=true; btn.textContent='กำลังเข้าสู่ระบบ...';
    const {data,error}=await sb.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});
    btn.disabled=false; btn.innerHTML='<i class="fa-solid fa-arrow-right-to-bracket"></i> เข้าสู่ระบบ';
    if(error) return swalError('เข้าสู่ระบบไม่สำเร็จ',error);
    const profile=await ensureStaff(data.session);
    if(!profile){ await sb.auth.signOut(); return Swal.fire({icon:'error',title:'ไม่มีสิทธิ์ Tutor OS',text:'บัญชีนี้ยังไม่ได้รับสิทธิ์ Staff / Manager / Admin',confirmButtonColor:'#0ea5e9'}); }
    await enterApp(data.session,profile);
  });
  $('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload();};

  async function safe(name,promise,def=[]){
    try{
      const {data,error}=await promise;
      if(error) throw error;
      return data ?? def;
    }catch(e){
      const msg=`${name}: ${errorText(e)}`;
      state.errors.push(msg);
      if(/^os_/.test(name) || /Tutor OS/i.test(msg)) state.systemReady=false;
      console.warn('[Tutor OS]',msg);
      return def;
    }
  }

  async function loadAll(show=true){
    if(state.loading) return;
    state.loading=true; state.errors=[];
    if(show) setConnection('syncing');
    const queries = [
      ['tutors',sb.from('tutors').select('*').order('sort_order')],
      ['courses',sb.from('courses').select('*').order('sort_order')],
      ['enrollments',isAdmin()?sb.from('enrollments').select('*').order('created_at',{ascending:false}).limit(1000):Promise.resolve({data:[],error:null})],
      ['payments',isAdmin()?sb.from('payments').select('*').order('created_at',{ascending:false}).limit(1000):Promise.resolve({data:[],error:null})],
      ['tutorApplications',isAdmin()?sb.from('tutor_applications').select('*').order('created_at',{ascending:false}).limit(300):Promise.resolve({data:[],error:null})],
      ['speakers',isAdmin()?sb.from('speaker_requests').select('*').order('created_at',{ascending:false}).limit(300):Promise.resolve({data:[],error:null})],
      ['schedules',sb.from('tutor_schedules').select('*')],
      ['scheduleTemplates',sb.from('schedule_templates').select('*').order('sort_order')],
      ['promotions',isAdmin()?sb.from('promotions').select('*').order('created_at',{ascending:false}):Promise.resolve({data:[],error:null})],
      ['prices',isAdmin()?sb.from('course_prices').select('*'):Promise.resolve({data:[],error:null})],
      ['students',sb.from('os_students').select('*').order('updated_at',{ascending:false})],
      ['studentCourses',sb.from('os_student_course_enrollments').select('*').order('created_at',{ascending:false})],
      ['crm',sb.from('os_crm_contacts').select('*').order('updated_at',{ascending:false})],
      ['attendanceSessions',sb.from('os_attendance_sessions').select('*').order('session_date',{ascending:false}).limit(500)],
      ['attendance',sb.from('os_student_attendance').select('*').order('created_at',{ascending:false}).limit(3000)],
      ['teachingLogs',sb.from('os_teaching_logs').select('*').order('lesson_date',{ascending:false}).limit(1000)],
      ['learningTopics',sb.from('os_learning_topics').select('*').order('sort_order')],
      ['learningAssets',sb.from('os_learning_assets').select('*').order('sort_order')],
      ['learningAssignments',sb.from('os_learning_assignments').select('*')],
      ['tasks',sb.from('os_tasks').select('*').order('created_at',{ascending:false})],
      ['announcements',sb.from('os_announcements').select('*').order('publish_at',{ascending:false})],
      ['financeEntries',isAdmin()?sb.from('os_finance_entries').select('*').order('transaction_date',{ascending:false}):Promise.resolve({data:[],error:null})],
      ['paymentSlips',isAdmin()?sb.from('os_payment_slips').select('*').order('created_at',{ascending:false}):Promise.resolve({data:[],error:null})],
      ['library',sb.from('os_library_items').select('*').order('sort_order')],
      ['hr',isAdmin()?sb.from('os_hr_entries').select('*').order('entry_date',{ascending:false}):Promise.resolve({data:[],error:null})],
      ['courseRequests',sb.from('os_course_requests').select('*').order('created_at',{ascending:false})],
      ['quickReplies',sb.from('os_quick_replies').select('*').order('sort_order')],
      ['osSettings',sb.from('os_settings').select('*')],
      ['staffProfiles',sb.from('os_staff_profiles').select('*').order('display_name')]
    ];
    const results=await Promise.all(queries.map(async ([key,q])=>[key,await safe(key,q,[])]));
    results.forEach(([key,val])=>state[key]=val);
    state.systemReady = !state.errors.some(x=>x.includes('os_')&&/does not exist|schema cache|permission denied/i.test(x));
    state.loading=false; setConnection(state.systemReady?'connected':'warning'); render();
  }

  function setConnection(mode){
    const dot=$('connectionDot'),txt=$('connectionText');
    const map={connected:['#10b981','Connected'],syncing:['#f59e0b','Syncing…'],warning:['#f59e0b','Core only'],error:['#f43f5e','Disconnected']};
    const [c,t]=map[mode]||map.connected; dot.style.background=c; txt.textContent=t;
  }

  function routeFromUrl(){
    const q=new URLSearchParams(location.search); const section=q.get('section');
    if(section && $(`section-${section}`) && !(section==='finance'&&!isAdmin())) state.section=section;
    activateSection(state.section,false);
  }
  function activateSection(section,push=true){
    state.section=section;
    $$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.section===section));
    $$('.section').forEach(s=>s.classList.toggle('active',s.id===`section-${section}`));
    if(push){const u=new URL(location.href);u.searchParams.set('section',section);history.replaceState(null,'',u);}
    renderSection(section);
  }
  $$('.nav-btn').forEach(b=>b.onclick=()=>activateSection(b.dataset.section));

  function pageHead(kicker,title,sub,actions=''){
    return `<div class="page-head"><div><div class="page-kicker">${esc(kicker)}</div><h1 class="page-title">${esc(title)}</h1><p class="page-sub">${esc(sub)}</p></div><div class="toolbar">${actions}</div></div>`;
  }
  function metric(icon,label,value,note,tone='#eff6ff'){
    return `<article class="aw-card metric" style="--glow:${tone}"><div class="metric-icon"><i class="${icon}"></i></div><div><div class="metric-value">${esc(value)}</div><div class="metric-label">${esc(label)}</div><div class="metric-note">${esc(note)}</div></div></article>`;
  }
  function connectedCard(icon,title,desc,href,label='เปิดระบบ'){
    return `<article class="aw-card module-card"><div class="module-icon"><i class="${icon}"></i></div><h3>${esc(title)}</h3><p>${esc(desc)}</p><div class="module-actions"><a class="aw-btn small" href="${href}">${esc(label)} <i class="fa-solid fa-arrow-up-right-from-square"></i></a></div></article>`;
  }
  function tabs(section,items){
    const active=state.subtab[section];
    return `<div class="tabs">${items.map(([id,label,icon])=>`<button class="tab-btn ${active===id?'active':''}" data-subtab-section="${section}" data-subtab="${id}">${icon?`<i class="${icon}" style="margin-right:5px"></i>`:''}${esc(label)}</button>`).join('')}</div>`;
  }
  function bindTabs(root){
    $$('[data-subtab]',root).forEach(b=>b.onclick=()=>{state.subtab[b.dataset.subtabSection]=b.dataset.subtab;renderSection(b.dataset.subtabSection);});
  }

  function render(){ renderSection(state.section); }
  function renderSection(section){
    const el=$(`section-${section}`); if(!el)return;
    ({overview:renderOverview,students:renderStudents,courses:renderCourses,teaching:renderTeaching,finance:renderFinance,team:renderTeam,reports:renderReports,settings:renderSettings}[section]||renderOverview)(el);
  }

  function renderOverview(el){
    const pending=state.payments.filter(x=>x.status==='pending').length;
    const activeStudents=state.students.filter(x=>!x.archived&&x.status==='active').length;
    const openTasks=state.tasks.filter(x=>!x.completed).length;
    const todaySessions=state.attendanceSessions.filter(x=>x.session_date===today()&&x.status!=='cancelled').length;
    const pendingApps=state.tutorApplications.filter(x=>['new','reviewing'].includes(x.status)).length;
    el.innerHTML = pageHead('Tutor Operations','Tutor OS','ศูนย์กลางการทำงานสำหรับนักเรียน คอร์ส การสอน การเงิน และทีมงาน',`<button class="aw-btn" id="refreshAll"><i class="fa-solid fa-rotate"></i> รีเฟรช</button>`) +
    `<article class="aw-card hero"><div class="hero-inner"><div><span class="hero-chip"><i class="fa-solid fa-wand-magic-sparkles"></i> Unified AreWarin Workspace</span><h2>งานทุกส่วนเชื่อมกัน<br><span>โดยไม่สร้างข้อมูลซ้ำ</span></h2><p>ข้อมูลสมัครเรียนและชำระเงินมาจากระบบหลัก ส่วน Attendance, Learning, CRM, Tasks, Library และ HR ถูกต่อยอดใน Tutor OS โดยยังอ้างอิง Course / Tutor / Student เดิม</p></div><div class="hero-health"><div class="health-box"><small>Role</small><b>${esc(state.role)}</b><span>${isAdmin()?'Full operations':'Teaching workspace'}</span></div><div class="health-box"><small>Database</small><b>${state.systemReady?'Ready':'Upgrade'}</b><span>${state.systemReady?'Tutor OS schema':'Run V14 SQL'}</span></div><div class="health-box"><small>วันนี้</small><b>${todaySessions}</b><span>คาบเรียน</span></div><div class="health-box"><small>งานค้าง</small><b>${openTasks}</b><span>Tasks</span></div></div></div></article>
    <div class="metric-grid">
      ${metric('fa-solid fa-user-graduate','นักเรียน Active',activeStudents,'Operational records','#e0f2fe')}
      ${metric('fa-solid fa-book-open','คอร์สเปิดสอน',state.courses.filter(x=>x.active).length,'จาก Manager','#ede9fe')}
      ${metric('fa-solid fa-user-tie','ติวเตอร์',state.tutors.filter(x=>x.active).length,'ทีมผู้สอน','#dcfce7')}
      ${metric('fa-solid fa-wallet','รอตรวจชำระ',isAdmin()?pending:'—','จากระบบสมัคร','#fef3c7')}
      ${metric('fa-solid fa-user-plus','ใบสมัครติวเตอร์',isAdmin()?pendingApps:'—','รอตรวจ','#fae8ff')}
      ${metric('fa-solid fa-list-check','Tasks',openTasks,'ยังไม่เสร็จ','#e0e7ff')}
    </div>
    <div class="grid-2" style="margin-top:12px">
      <div class="aw-card panel"><div class="panel-head"><div><h3>Connected lifecycle</h3><p>ข้อมูลหนึ่งชุดเดินต่อกันตั้งแต่สมัครจนถึงการสอน</p></div><span class="aw-tag">Shared source</span></div><div class="workflow">
        ${[['01','สมัคร','Enrollment'],['02','ชำระ','Payment'],['03','จัดคอร์ส','Course'],['04','เข้าเรียน','Attendance'],['05','ติดตาม','Learning / CRM']].map(x=>`<div class="workflow-step"><div class="no">${x[0]}</div><b>${x[1]}</b><small>${x[2]}</small></div>`).join('')}
      </div></div>
      <div class="aw-card panel"><div class="panel-head"><div><h3>งานล่าสุด</h3><p>คาบเรียน งาน และรายการที่ต้องติดตาม</p></div></div><div class="list">${recentActivity().slice(0,6).map(x=>`<div class="list-item"><div class="list-item-head"><div><h4>${esc(x.title)}</h4><p>${esc(x.detail)}</p></div><span class="aw-tag">${esc(x.when)}</span></div></div>`).join('')||'<div class="empty">ยังไม่มี activity</div>'}</div></div>
    </div>
    <div style="margin-top:12px" class="grid-4">
      ${connectedCard('fa-solid fa-file-signature','Admissions','ตรวจใบสมัครและสถานะการลงทะเบียนจากระบบ Manager','../manager/?section=enrollments','เปิด Enrollment')}
      ${connectedCard('fa-regular fa-calendar','Schedule & Capacity','จัดตารางรายติวเตอร์ ช่วงเวลา และ Capacity','../manager/?section=schedule','เปิดตาราง')}
      ${connectedCard('fa-solid fa-tags','Pricing & Promotion','ราคาแพ็กเกจและโค้ดส่วนลด','../manager/?section=prices','จัดราคา')}
      ${connectedCard('fa-solid fa-microphone','Speaker Requests','คำขอจ้างวิทยากรจากเว็บไซต์','../manager/?section=speakers','เปิดคำขอ')}
    </div>`;
    $('refreshAll').onclick=()=>loadAll();
  }

  function recentActivity(){
    const a=[];
    state.tasks.filter(x=>!x.completed).slice(0,4).forEach(x=>a.push({title:`Task: ${x.task_text}`,detail:x.note||'งานทีม',when:x.due_date?date(x.due_date):'Open'}));
    state.attendanceSessions.slice(0,4).forEach(x=>a.push({title:`คาบเรียน: ${x.title||course(x.course_id)?.name||'Session'}`,detail:`${date(x.session_date)} ${x.start_time?String(x.start_time).slice(0,5):''}`,when:x.status}));
    return a;
  }

  function renderStudents(el){
    const tab=state.subtab.students;
    el.innerHTML=pageHead('Students','นักเรียน & CRM','ดูข้อมูลที่เชื่อมจากการสมัคร พร้อมบันทึกงานติดตามและ Student Portal',`<button class="aw-btn sky" id="addStudent"><i class="fa-solid fa-plus"></i> เพิ่มนักเรียน</button><button class="aw-btn" id="refreshStudents"><i class="fa-solid fa-rotate"></i></button>`) + tabs('students',[
      ['students','นักเรียน','fa-solid fa-user-graduate'],['crm','CRM & ผู้ปกครอง','fa-solid fa-address-book'],['portal','Portal Preview','fa-solid fa-display']
    ]) + `<div id="studentsBody"></div>`;
    bindTabs(el); $('addStudent').onclick=()=>openStudentModal(); $('refreshStudents').onclick=()=>loadAll();
    const body=$('studentsBody');
    if(tab==='crm') renderCRM(body); else if(tab==='portal') renderPortal(body); else renderStudentList(body);
  }

  function renderStudentList(root){
    root.innerHTML=`<div class="aw-card panel"><div class="panel-head"><div><h3>Student records</h3><p>ระบบหลักจะ Sync ผู้สมัครตามเบอร์โทรเข้ามาอัตโนมัติ</p></div><div class="toolbar"><div class="search"><i class="fa-solid fa-magnifying-glass"></i><input id="studentSearch" class="aw-input" placeholder="ค้นหาชื่อ เบอร์ โรงเรียน คอร์ส"></div><select id="studentFilter" class="aw-input" style="width:auto"><option value="all">ทุกสถานะ</option><option value="active">Active</option><option value="pending">Pending</option><option value="archived">Archived</option></select></div></div><div class="table-wrap"><table class="table"><thead><tr><th>นักเรียน</th><th>ติดต่อ</th><th>คอร์ส</th><th>สถานะ</th><th>อัปเดต</th><th></th></tr></thead><tbody id="studentRows"></tbody></table></div></div>`;
    const renderRows=()=>{
      const q=$('studentSearch').value.trim().toLowerCase(),f=$('studentFilter').value;
      const rows=state.students.filter(s=>(f==='all'||(f==='archived'?s.archived:s.status===f))&&(!q||[s.display_name,s.nickname,s.phone,s.email,s.school,s.course_summary].join(' ').toLowerCase().includes(q)));
      $('studentRows').innerHTML=rows.map(s=>{const cs=studentCourseRows(s.id).filter(x=>x.status!=='cancelled');return `<tr><td><div class="person"><div class="avatar">${esc(initials(s.display_name))}</div><div><div class="row-title">${esc(s.display_name)}</div><div class="row-sub">${esc(s.nickname||'')} ${s.school?'• '+esc(s.school):''}</div></div></div></td><td>${esc(s.phone||'—')}<div class="row-sub">${esc(s.email||'')}</div></td><td>${cs.slice(0,2).map(x=>`<div>${esc(x.course_label||course(x.course_id)?.name||'คอร์ส')}</div>`).join('')||esc(s.course_summary||'—')}</td><td><span class="status ${studentStatusClass(s.status)}">${esc(s.archived?'archived':s.status)}</span></td><td>${date(s.updated_at)}</td><td><button class="aw-btn small" data-edit-student="${s.id}">เปิด</button></td></tr>`}).join('')||'<tr><td colspan="6"><div class="empty">ยังไม่มีข้อมูลนักเรียน — ระบบจะ Sync จาก Enrollment หลังรัน SQL V14</div></td></tr>';
      $$('[data-edit-student]',root).forEach(b=>b.onclick=()=>openStudentModal(b.dataset.editStudent));
    };
    $('studentSearch').oninput=renderRows;$('studentFilter').onchange=renderRows;renderRows();
  }

  function openStudentModal(id=null){
    const s=id?student(id):null;
    openModal(s?'ข้อมูลนักเรียน':'เพิ่มนักเรียนใน Tutor OS',`<form id="studentForm" class="form-grid">
      <label class="aw-label wide">ชื่อที่แสดง *<input class="aw-input" name="display_name" required value="${esc(s?.display_name||'')}"></label>
      <label class="aw-label">ชื่อเล่น<input class="aw-input" name="nickname" value="${esc(s?.nickname||'')}"></label>
      <label class="aw-label">สถานะ<select class="aw-input" name="status"><option value="active" ${s?.status==='active'?'selected':''}>active</option><option value="pending" ${s?.status==='pending'?'selected':''}>pending</option><option value="inactive" ${s?.status==='inactive'?'selected':''}>inactive</option><option value="archived" ${s?.status==='archived'?'selected':''}>archived</option></select></label>
      <label class="aw-label">เบอร์โทร<input class="aw-input" name="phone" value="${esc(s?.phone||'')}"></label>
      <label class="aw-label">อีเมล<input class="aw-input" type="email" name="email" value="${esc(s?.email||'')}"></label>
      <label class="aw-label">LINE<input class="aw-input" name="line_id" value="${esc(s?.line_id||'')}"></label>
      <label class="aw-label">โรงเรียน<input class="aw-input" name="school" value="${esc(s?.school||'')}"></label>
      <label class="aw-label">ระดับชั้น<input class="aw-input" name="grade" value="${esc(s?.grade||'')}"></label>
      <label class="aw-label">ผู้ปกครอง<input class="aw-input" name="parent_name" value="${esc(s?.parent_name||'')}"></label>
      <label class="aw-label">เบอร์ผู้ปกครอง<input class="aw-input" name="parent_phone" value="${esc(s?.parent_phone||'')}"></label>
      <label class="aw-label wide">บันทึกภายใน<textarea class="aw-input" name="notes">${esc(s?.notes||'')}</textarea></label>
    </form>`, `<button class="aw-btn" data-modal-close>ยกเลิก</button>${s&&isAdmin()?'<button class="aw-btn danger" id="archiveStudent">เก็บเข้าคลัง</button>':''}<button class="aw-btn primary" id="saveStudent">บันทึก</button>`);
    $('saveStudent').onclick=async()=>{
      const fd=new FormData($('studentForm'));const row=Object.fromEntries(fd.entries());row.phone_key=slugPhone(row.phone)||`manual:${s?.id||crypto.randomUUID()}`;row.archived=row.status==='archived';
      try{let q=s?sb.from('os_students').update(row).eq('id',s.id):sb.from('os_students').insert(row);const{error}=await q;if(error)throw error;closeModal();await loadAll(false);toast('บันทึกนักเรียนแล้ว');}catch(e){swalError('บันทึกไม่สำเร็จ',e)}
    };
    if($('archiveStudent')) $('archiveStudent').onclick=async()=>{const r=await Swal.fire({icon:'warning',title:'เก็บนักเรียนเข้าคลัง?',showCancelButton:true,confirmButtonText:'เก็บเข้าคลัง'});if(!r.isConfirmed)return;const{data,error}=await sb.rpc('os_archive_student',{p_student_id:s.id,p_mode:'archive'});if(error)return swalError('ดำเนินการไม่สำเร็จ',error);closeModal();await loadAll(false);toast(data?.message||'เรียบร้อย');};
  }

  function renderCRM(root){
    root.innerHTML=`<div class="grid-3"><div class="aw-card panel"><div class="panel-head"><div><h3>Pipeline</h3><p>ผู้สนใจและผู้ปกครองที่ต้องติดตาม</p></div><button class="aw-btn sky small" id="addCRM"><i class="fa-solid fa-plus"></i> เพิ่ม</button></div>${['lead','contacted','trial','ready','closed'].map(stage=>`<div class="list-item" style="margin-bottom:7px"><div class="list-item-head"><h4>${stage}</h4><b>${state.crm.filter(x=>x.stage===stage).length}</b></div></div>`).join('')}</div><div class="aw-card panel" style="grid-column:span 2"><div class="panel-head"><div><h3>CRM records</h3><p>คลิกเพื่อแก้ไขสถานะและนัดติดตาม</p></div></div><div class="list">${state.crm.map(x=>`<button class="list-item" style="text-align:left" data-crm="${x.id}"><div class="list-item-head"><div><h4>${esc(x.name)}</h4><p>${esc(x.phone||'')} ${x.guardian_name?'• ผู้ปกครอง '+esc(x.guardian_name):''}</p></div><span class="status blue">${esc(x.stage)}</span></div>${x.next_follow_up?`<p><i class="fa-regular fa-clock"></i> นัดติดตาม ${dateTime(x.next_follow_up)}</p>`:''}</button>`).join('')||'<div class="empty">ยังไม่มี CRM</div>'}</div></div></div>`;
    $('addCRM').onclick=()=>openCRM();$$('[data-crm]',root).forEach(b=>b.onclick=()=>openCRM(b.dataset.crm));
  }
  function openCRM(id=null){const x=id?state.crm.find(v=>v.id===id):null;openModal(x?'แก้ไข CRM':'เพิ่มผู้สนใจ',`<form id="crmForm" class="form-grid"><label class="aw-label wide">ชื่อ *<input class="aw-input" name="name" required value="${esc(x?.name||'')}"></label><label class="aw-label">โทร<input class="aw-input" name="phone" value="${esc(x?.phone||'')}"></label><label class="aw-label">LINE<input class="aw-input" name="line_id" value="${esc(x?.line_id||'')}"></label><label class="aw-label">อีเมล<input class="aw-input" name="email" value="${esc(x?.email||'')}"></label><label class="aw-label">ผู้ปกครอง<input class="aw-input" name="guardian_name" value="${esc(x?.guardian_name||'')}"></label><label class="aw-label">เบอร์ผู้ปกครอง<input class="aw-input" name="guardian_phone" value="${esc(x?.guardian_phone||'')}"></label><label class="aw-label">Stage<select class="aw-input" name="stage">${['lead','contacted','trial','ready','closed'].map(s=>`<option ${x?.stage===s?'selected':''}>${s}</option>`).join('')}</select></label><label class="aw-label">นัดติดตาม<input type="datetime-local" class="aw-input" name="next_follow_up" value="${x?.next_follow_up?new Date(x.next_follow_up).toISOString().slice(0,16):''}"></label><label class="aw-label wide">Notes<textarea class="aw-input" name="notes">${esc(x?.notes||'')}</textarea></label></form>`,`<button class="aw-btn" data-modal-close>ยกเลิก</button>${x?'<button class="aw-btn danger" id="deleteCRM">ลบ</button>':''}<button class="aw-btn primary" id="saveCRM">บันทึก</button>`);$('saveCRM').onclick=async()=>{const fd=new FormData($('crmForm')),row=Object.fromEntries(fd.entries());row.next_follow_up=row.next_follow_up?new Date(row.next_follow_up).toISOString():null;try{const{error}=await(x?sb.from('os_crm_contacts').update(row).eq('id',x.id):sb.from('os_crm_contacts').insert(row));if(error)throw error;closeModal();await loadAll(false);toast('บันทึก CRM แล้ว')}catch(e){swalError('บันทึกไม่สำเร็จ',e)}};if($('deleteCRM'))$('deleteCRM').onclick=async()=>{if(!confirm('ลบ CRM นี้?'))return;const{error}=await sb.from('os_crm_contacts').delete().eq('id',x.id);if(error)return swalError('ลบไม่สำเร็จ',error);closeModal();await loadAll(false);toast('ลบแล้ว')};}

  function renderPortal(root){
    root.innerHTML=`<div class="grid-2"><div class="aw-card panel"><div class="panel-head"><div><h3>Student Portal Preview</h3><p>เลือกนักเรียนเพื่อดูข้อมูลที่ Portal ควรแสดง</p></div></div><select id="portalStudent" class="aw-input"><option value="">เลือกนักเรียน</option>${state.students.filter(x=>!x.archived).map(s=>`<option value="${s.id}">${esc(s.display_name)}</option>`).join('')}</select><div id="portalPreview" style="margin-top:12px"></div></div><div class="aw-card panel"><div class="panel-head"><div><h3>ประกาศที่กำลังแสดง</h3><p>ใช้กับ Student Experience</p></div></div><div class="list">${activeAnnouncements().map(a=>`<div class="list-item"><h4>${esc(a.title)}</h4><p>${esc(a.body)}</p></div>`).join('')||'<div class="empty">ไม่มีประกาศ</div>'}</div></div></div>`;
    $('portalStudent').onchange=e=>{const s=student(e.target.value);if(!s){$('portalPreview').innerHTML='';return}const sc=studentCourseRows(s.id).filter(x=>x.status==='active');const att=state.attendance.filter(a=>a.student_id===s.id);const present=att.filter(a=>['present','late'].includes(a.status)).length;$('portalPreview').innerHTML=`<div class="aw-card" style="padding:15px;background:#f8fafc"><div class="person"><div class="avatar">${esc(initials(s.display_name))}</div><div><div class="row-title">${esc(s.display_name)}</div><div class="row-sub">Student ID ${esc(s.id.slice(0,8))}</div></div></div><div class="grid-2" style="margin-top:12px"><div class="list-item"><h4>คอร์สที่ลง</h4><p>${sc.map(x=>esc(x.course_label||course(x.course_id)?.name||'คอร์ส')).join('<br>')||'—'}</p></div><div class="list-item"><h4>Attendance</h4><p>${present}/${att.length||0} ครั้ง</p></div></div></div>`;};
  }

  function activeAnnouncements(){const now=Date.now();return state.announcements.filter(a=>a.is_active!==false&&new Date(a.publish_at||0).getTime()<=now&&(!a.expires_at||new Date(a.expires_at).getTime()>now));}

  function renderCourses(el){
    const tab=state.subtab.courses;
    el.innerHTML=pageHead('Courses','คอร์ส & สมัคร','คอร์สหลักใช้ข้อมูลเดียวกับ Manager และเชื่อมต่อ Pricing / Schedule / Admissions',`<a class="aw-btn sky" href="../manager/?section=courses"><i class="fa-solid fa-pen"></i> จัดคอร์สใน Manager</a>`) + tabs('courses',[['courses','คอร์สหลัก','fa-solid fa-book'],['requests','คำขอเปิดคอร์ส','fa-solid fa-file-circle-plus'],['admissions','Admissions & Pricing','fa-solid fa-diagram-project']]) + `<div id="coursesBody"></div>`;
    bindTabs(el);const root=$('coursesBody');if(tab==='requests')renderCourseRequests(root);else if(tab==='admissions')renderAdmissions(root);else renderCourseList(root);
  }
  function renderCourseList(root){root.innerHTML=`<div class="grid-3">${state.courses.map(c=>{const t=tutor(c.tutor_id);const count=new Set(state.studentCourses.filter(x=>x.course_id===c.id&&x.status==='active').map(x=>x.student_id)).size;return `<article class="aw-card module-card"><div class="module-icon"><i class="fa-solid fa-dna"></i></div><div style="display:flex;justify-content:space-between;gap:8px"><h3>${esc(c.name)}</h3><span class="status ${c.active?'green':'red'}">${c.active?'OPEN':'OFF'}</span></div><p>${esc(c.short_detail||c.full_description||'')}<br><b>${esc(t?.display_name||'ไม่ระบุติวเตอร์')}</b> • ${count} นักเรียน</p><div class="module-actions"><a class="aw-btn small" href="../manager/?section=courses">แก้ไข</a><button class="aw-btn small" data-course-students="${c.id}">นักเรียน</button></div></article>`}).join('')||'<div class="empty">ยังไม่มีคอร์ส</div>'}</div>`;$$('[data-course-students]',root).forEach(b=>b.onclick=()=>{const c=course(b.dataset.courseStudents);const rows=state.studentCourses.filter(x=>x.course_id===c.id&&x.status==='active');openModal(`นักเรียน · ${c.name}`,`<div class="list">${rows.map(r=>{const s=student(r.student_id);return `<div class="list-item"><h4>${esc(s?.display_name||'Unknown')}</h4><p>${esc(s?.phone||'')} • ใช้ ${num(r.hours_used)}/${num(r.hours_total)} ชม.</p></div>`}).join('')||'<div class="empty">ยังไม่มีนักเรียน</div>'}</div>`,`<button class="aw-btn primary" data-modal-close>ปิด</button>`);});}
  function renderCourseRequests(root){root.innerHTML=`<div class="grid-2"><div class="aw-card panel"><div class="panel-head"><div><h3>คำขอเปิดคอร์ส</h3><p>ติวเตอร์เสนอคอร์สใหม่ก่อนสร้างใน Catalog กลาง</p></div><button id="newCourseRequest" class="aw-btn sky small"><i class="fa-solid fa-plus"></i> ส่งคำขอ</button></div><div class="list">${state.courseRequests.map(x=>`<div class="list-item"><div class="list-item-head"><div><h4>${esc(x.title)}</h4><p>${esc(x.description||'')}</p></div><span class="status ${x.status==='approved'?'green':x.status==='rejected'?'red':'amber'}">${esc(x.status)}</span></div><p>${num(x.proposed_hours)||0} ชม. • ${money(x.proposed_price||0)}</p>${isAdmin()&&x.status==='pending'?`<div class="module-actions" style="margin-top:8px"><button class="aw-btn success small" data-review-course="${x.id}:approved">อนุมัติ</button><button class="aw-btn danger small" data-review-course="${x.id}:rejected">ไม่อนุมัติ</button></div>`:''}</div>`).join('')||'<div class="empty">ไม่มีคำขอ</div>'}</div></div><div class="aw-card panel"><div class="panel-head"><div><h3>Workflow</h3><p>Request → Review → Create Course → Pricing → Schedule</p></div></div><div class="section-note"><b>เมื่ออนุมัติ</b> ให้สร้าง Course จริงใน Manager เพื่อให้หน้าเว็บสมัครเรียนเห็นทันที โดยข้อมูล Tutor OS จะอ้างอิง Course UUID เดียวกัน</div><div class="module-actions" style="margin-top:12px"><a class="aw-btn" href="../manager/?section=courses">สร้างคอร์ส</a><a class="aw-btn" href="../manager/?section=prices">กำหนดราคา</a><a class="aw-btn" href="../manager/?section=schedule">เปิดรอบเรียน</a></div></div></div>`;$('newCourseRequest').onclick=openCourseRequest;$$('[data-review-course]',root).forEach(b=>b.onclick=async()=>{const[id,status]=b.dataset.reviewCourse.split(':');const note=prompt('หมายเหตุ (เว้นว่างได้)','')||'';const{error}=await sb.from('os_course_requests').update({status,admin_note:note,reviewed_by:state.session.user.id,reviewed_at:new Date().toISOString()}).eq('id',id);if(error)return swalError('อัปเดตไม่สำเร็จ',error);await loadAll(false);toast('อัปเดตคำขอแล้ว')});}
  function openCourseRequest(){openModal('ส่งคำขอเปิดคอร์ส',`<form id="courseRequestForm" class="form-grid"><label class="aw-label wide">ชื่อคอร์ส *<input class="aw-input" name="title" required></label><label class="aw-label wide">รายละเอียด<textarea class="aw-input" name="description"></textarea></label><label class="aw-label">ระดับผู้เรียน (คั่นด้วย ,)<input class="aw-input" name="levels"></label><label class="aw-label">ชั่วโมงที่เสนอ<input type="number" step="0.5" class="aw-input" name="hours"></label><label class="aw-label">ราคาที่เสนอ<input type="number" step="1" class="aw-input" name="price"></label></form>`,`<button class="aw-btn" data-modal-close>ยกเลิก</button><button class="aw-btn primary" id="saveCourseRequest">ส่งคำขอ</button>`);$('saveCourseRequest').onclick=async()=>{const fd=new FormData($('courseRequestForm'));const row={requested_by:state.session.user.id,title:fd.get('title'),description:fd.get('description'),target_levels:String(fd.get('levels')||'').split(',').map(x=>x.trim()).filter(Boolean),proposed_hours:num(fd.get('hours')),proposed_price:num(fd.get('price'))};const{error}=await sb.from('os_course_requests').insert(row);if(error)return swalError('ส่งคำขอไม่สำเร็จ',error);closeModal();await loadAll(false);toast('ส่งคำขอแล้ว')};}
  function renderAdmissions(root){root.innerHTML=`<div class="grid-3">${connectedCard('fa-solid fa-file-signature','ใบสมัคร & Enrollment','ตรวจผู้สมัครเดิม/ใหม่ เปลี่ยนสถานะ และดูใบเสร็จ','../manager/?section=enrollments','เปิดใบสมัคร')}${connectedCard('fa-regular fa-calendar-days','Schedule & Capacity','ช่วงเวลาสอนราย Tutor และจำนวนที่รับพร้อมกัน','../manager/?section=schedule','จัดตาราง')}${connectedCard('fa-solid fa-ticket','Promotion','โค้ดส่วนลด ช่วงเวลา และสถานะการใช้งาน','../manager/?section=promotions','จัดโปรโมชั่น')}${connectedCard('fa-solid fa-tags','Course Pricing','แพ็กเกจรายปี 30/20/10 ชั่วโมง และรายชั่วโมง','../manager/?section=prices','จัดราคา')}${connectedCard('fa-solid fa-wallet','Payment Review','ตรวจสลิปและยืนยันยอดก่อนออกใบเสร็จ','../manager/?section=payments','ตรวจการชำระ')}${connectedCard('fa-solid fa-receipt','Receipt Settings','Logo ลายเซ็น ข้อมูลธุรกิจ และเลขใบเสร็จ','../manager/?section=receipt','ตั้งค่าใบเสร็จ')}</div>`;}

  function renderTeaching(el){
    const tab=state.subtab.teaching;
    el.innerHTML=pageHead('Teaching','การสอน','Attendance, Teaching Log, Learning Portal, Tasks, Announcements และตารางรวม',`<button class="aw-btn" id="refreshTeaching"><i class="fa-solid fa-rotate"></i> รีเฟรช</button>`) + tabs('teaching',[['attendance','เช็กชื่อ','fa-regular fa-clock'],['logs','บันทึกหลังสอน','fa-solid fa-pen-to-square'],['learning','เรียนย้อนหลัง','fa-solid fa-circle-play'],['tasks','Tasks','fa-solid fa-list-check'],['announcements','ประกาศ','fa-solid fa-bullhorn'],['schedule','ตารางรวม','fa-regular fa-calendar']]) + `<div id="teachingBody"></div>`;
    bindTabs(el);$('refreshTeaching').onclick=()=>loadAll();const root=$('teachingBody');({attendance:renderAttendance,logs:renderTeachingLogs,learning:renderLearning,tasks:renderTasks,announcements:renderAnnouncements,schedule:renderSchedule}[tab]||renderAttendance)(root);
  }

  function renderAttendance(root){const sessions=state.attendanceSessions;root.innerHTML=`<div class="grid-2"><div class="aw-card panel"><div class="panel-head"><div><h3>Attendance sessions</h3><p>เปิดคาบและบันทึกมาเรียน / สาย / ขาด / ลา</p></div><button class="aw-btn sky small" id="newSession"><i class="fa-solid fa-plus"></i> เปิดคาบ</button></div><div class="list">${sessions.slice(0,40).map(s=>{const c=course(s.course_id),t=tutor(s.tutor_id),count=state.attendance.filter(a=>a.session_id===s.id&&['present','late'].includes(a.status)).length;return `<button class="list-item" style="text-align:left" data-session="${s.id}"><div class="list-item-head"><div><h4>${esc(s.title||c?.name||'Session')}</h4><p>${date(s.session_date)} ${s.start_time?String(s.start_time).slice(0,5):''} • ${esc(t?.display_name||'')}</p></div><span class="status ${s.status==='completed'?'green':'blue'}">${esc(s.status)}</span></div><p>${count} คนเช็กชื่อแล้ว</p></button>`}).join('')||'<div class="empty">ยังไม่มีคาบเรียน</div>'}</div></div><div class="aw-card panel"><div class="panel-head"><div><h3>วันนี้</h3><p>คาบที่กำหนดใน Tutor OS</p></div><span class="aw-tag">${today()}</span></div>${sessions.filter(x=>x.session_date===today()).map(s=>`<div class="list-item" style="margin-bottom:7px"><h4>${esc(s.title||course(s.course_id)?.name||'Session')}</h4><p>${String(s.start_time||'').slice(0,5)}–${String(s.end_time||'').slice(0,5)} • ${esc(tutor(s.tutor_id)?.display_name||'')}</p></div>`).join('')||'<div class="empty">วันนี้ยังไม่มีคาบ</div>'}</div></div>`;$('newSession').onclick=openSessionModal;$$('[data-session]',root).forEach(b=>b.onclick=()=>openRoster(b.dataset.session));}
  function openSessionModal(){openModal('เปิดคาบเรียน',`<form id="sessionForm" class="form-grid"><label class="aw-label wide">คอร์ส<select class="aw-input" name="course_id" required><option value="">เลือกคอร์ส</option>${state.courses.filter(x=>x.active).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label class="aw-label">ติวเตอร์<select class="aw-input" name="tutor_id"><option value="">ไม่ระบุ</option>${state.tutors.filter(x=>x.active).map(t=>`<option value="${t.id}">${esc(t.display_name)}</option>`).join('')}</select></label><label class="aw-label">วันที่<input type="date" class="aw-input" name="session_date" value="${today()}" required></label><label class="aw-label">เริ่ม<input type="time" class="aw-input" name="start_time"></label><label class="aw-label">สิ้นสุด<input type="time" class="aw-input" name="end_time"></label><label class="aw-label wide">ชื่อคาบ<input class="aw-input" name="title" placeholder="เช่น Chapter 3: Cell Biology"></label><label class="aw-label wide">หมายเหตุ<textarea class="aw-input" name="note"></textarea></label></form>`,`<button class="aw-btn" data-modal-close>ยกเลิก</button><button class="aw-btn primary" id="saveSession">เปิดคาบ</button>`);$('saveSession').onclick=async()=>{const row=Object.fromEntries(new FormData($('sessionForm')).entries());row.tutor_id=row.tutor_id||null;row.created_by=state.session.user.id;const{error}=await sb.from('os_attendance_sessions').insert(row);if(error)return swalError('เปิดคาบไม่สำเร็จ',error);closeModal();await loadAll(false);toast('เปิดคาบเรียนแล้ว')};}
  function openRoster(id){const sess=state.attendanceSessions.find(x=>x.id===id);if(!sess)return;const courseStudents=state.studentCourses.filter(x=>x.course_id===sess.course_id&&x.status==='active').map(x=>student(x.student_id)).filter(Boolean);openModal(`เช็กชื่อ · ${sess.title||course(sess.course_id)?.name||''}`,`<div class="section-note" style="margin-bottom:10px">${date(sess.session_date)} ${String(sess.start_time||'').slice(0,5)} • ${esc(tutor(sess.tutor_id)?.display_name||'')}</div><div class="list" id="rosterList">${courseStudents.map(s=>{const a=state.attendance.find(x=>x.session_id===id&&x.student_id===s.id);return `<div class="list-item"><div class="list-item-head"><div><h4>${esc(s.display_name)}</h4><p>${esc(s.phone||'')}</p></div><span class="status ${a?.status==='present'?'green':a?.status==='late'?'amber':a?.status==='absent'?'red':'blue'}">${esc(a?.status||'ยังไม่เช็ก')}</span></div><div class="module-actions" style="margin-top:8px">${[['present','มาเรียน','success'],['late','สาย','warn'],['absent','ขาด','danger'],['leave','ลา','']].map(x=>`<button class="aw-btn small ${x[2]}" data-attend="${s.id}:${x[0]}">${x[1]}</button>`).join('')}</div></div>`}).join('')||'<div class="empty">ยังไม่มีนักเรียนที่ผูกกับ Course UUID นี้</div>'}</div>`,`<button class="aw-btn" id="completeSession">ปิดคาบ</button><button class="aw-btn primary" data-modal-close>เสร็จ</button>`);$$('[data-attend]',$('modalRoot')).forEach(b=>b.onclick=async()=>{const[sid,status]=b.dataset.attend.split(':');const row={session_id:id,student_id:sid,status,checked_in_at:['present','late'].includes(status)?new Date().toISOString():null,source:'tutor-os'};const{error}=await sb.from('os_student_attendance').upsert(row,{onConflict:'session_id,student_id'});if(error)return swalError('เช็กชื่อไม่สำเร็จ',error);await loadAll(false);openRoster(id)});$('completeSession').onclick=async()=>{const{error}=await sb.from('os_attendance_sessions').update({status:'completed'}).eq('id',id);if(error)return swalError('ปิดคาบไม่สำเร็จ',error);closeModal();await loadAll(false);toast('ปิดคาบแล้ว')};}

  function renderTeachingLogs(root){root.innerHTML=`<div class="aw-card panel"><div class="panel-head"><div><h3>บันทึกหลังสอน</h3><p>หัวข้อ ชั่วโมง และผลการเรียนของแต่ละคาบ</p></div><button id="newTeachingLog" class="aw-btn sky small"><i class="fa-solid fa-plus"></i> เพิ่มบันทึก</button></div><div class="table-wrap"><table class="table"><thead><tr><th>วันที่</th><th>นักเรียน</th><th>คอร์ส</th><th>หัวข้อ</th><th>ชั่วโมง</th><th>ผู้สอน</th></tr></thead><tbody>${state.teachingLogs.map(x=>`<tr><td>${date(x.lesson_date)}</td><td>${esc(student(x.student_id)?.display_name||'—')}</td><td>${esc(course(x.course_id)?.name||'—')}</td><td><div class="row-title">${esc(x.topic)}</div><div class="row-sub">${esc(x.notes||'')}</div></td><td>${num(x.hours)}</td><td>${esc(tutor(x.tutor_id)?.display_name||'—')}</td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">ยังไม่มีบันทึก</div></td></tr>'}</tbody></table></div></div>`;$('newTeachingLog').onclick=openTeachingLog;}
  function openTeachingLog(){openModal('บันทึกหลังสอน',`<form id="logForm" class="form-grid"><label class="aw-label">นักเรียน<select class="aw-input" name="student_id"><option value="">ไม่ระบุ</option>${state.students.filter(x=>!x.archived).map(s=>`<option value="${s.id}">${esc(s.display_name)}</option>`).join('')}</select></label><label class="aw-label">คอร์ส<select class="aw-input" name="course_id"><option value="">ไม่ระบุ</option>${state.courses.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label class="aw-label">ติวเตอร์<select class="aw-input" name="tutor_id"><option value="">ไม่ระบุ</option>${state.tutors.map(t=>`<option value="${t.id}">${esc(t.display_name)}</option>`).join('')}</select></label><label class="aw-label">วันที่<input type="date" class="aw-input" name="lesson_date" value="${today()}"></label><label class="aw-label wide">หัวข้อ *<input class="aw-input" name="topic" required></label><label class="aw-label">ชั่วโมง<input type="number" min="0" step="0.25" class="aw-input" name="hours" value="1.5"></label><label class="aw-label wide">Notes<textarea class="aw-input" name="notes"></textarea></label><label class="aw-label wide">Outcome<textarea class="aw-input" name="outcome"></textarea></label></form>`,`<button class="aw-btn" data-modal-close>ยกเลิก</button><button class="aw-btn primary" id="saveLog">บันทึก</button>`);$('saveLog').onclick=async()=>{const row=Object.fromEntries(new FormData($('logForm')).entries());['student_id','course_id','tutor_id'].forEach(k=>row[k]=row[k]||null);row.hours=num(row.hours);row.created_by=state.session.user.id;const{error}=await sb.from('os_teaching_logs').insert(row);if(error)return swalError('บันทึกไม่สำเร็จ',error);closeModal();await loadAll(false);toast('บันทึกหลังสอนแล้ว')};}

  function renderLearning(root){root.innerHTML=`<div class="grid-2"><div class="aw-card panel"><div class="panel-head"><div><h3>Learning topics</h3><p>บทเรียนย้อนหลังตามคอร์ส</p></div><button class="aw-btn sky small" id="newTopic"><i class="fa-solid fa-plus"></i> หัวข้อ</button></div><div class="list">${state.learningTopics.map(t=>{const assets=state.learningAssets.filter(a=>a.topic_id===t.id);return `<button class="list-item" style="text-align:left" data-topic="${t.id}"><div class="list-item-head"><div><h4>${esc(t.title)}</h4><p>${esc(course(t.course_id)?.name||'')} • ${assets.length} resources</p></div><span class="status ${t.is_active?'green':'red'}">${t.is_active?'active':'hidden'}</span></div></button>`}).join('')||'<div class="empty">ยังไม่มีหัวข้อ</div>'}</div></div><div class="aw-card panel"><div class="panel-head"><div><h3>Portal Content</h3><p>วิดีโอ ชีท ไฟล์ และลิงก์</p></div></div><div class="section-note"><b>การเชื่อมข้อมูล:</b> Topic อ้างอิง Course UUID จากระบบหลัก จึงสามารถกำหนดสิทธิ์เป็นทั้งคอร์สหรือเฉพาะนักเรียนได้ โดยไม่สร้าง Course ซ้ำ</div><div class="module-actions" style="margin-top:12px"><button class="aw-btn" id="newAsset"><i class="fa-solid fa-paperclip"></i> เพิ่ม Resource</button><a class="aw-btn" href="?section=students">Portal Preview</a></div></div></div>`;$('newTopic').onclick=()=>openTopic();$('newAsset').onclick=()=>openAsset();$$('[data-topic]',root).forEach(b=>b.onclick=()=>openTopic(b.dataset.topic));}
  function openTopic(id=null){const t=id?state.learningTopics.find(x=>x.id===id):null;openModal(t?'แก้ไข Learning Topic':'เพิ่ม Learning Topic',`<form id="topicForm" class="form-grid"><label class="aw-label wide">คอร์ส<select class="aw-input" name="course_id" required><option value="">เลือก</option>${state.courses.map(c=>`<option value="${c.id}" ${t?.course_id===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label class="aw-label wide">ชื่อหัวข้อ *<input class="aw-input" name="title" required value="${esc(t?.title||'')}"></label><label class="aw-label wide">รายละเอียด<textarea class="aw-input" name="description">${esc(t?.description||'')}</textarea></label><label class="aw-label">ลำดับ<input type="number" class="aw-input" name="sort_order" value="${t?.sort_order??100}"></label><label class="checkbox-row"><input type="checkbox" name="is_active" ${t?.is_active===false?'':'checked'}> เปิดใช้งาน</label></form>`,`<button class="aw-btn" data-modal-close>ยกเลิก</button>${t?'<button class="aw-btn danger" id="deleteTopic">ลบ</button>':''}<button class="aw-btn primary" id="saveTopic">บันทึก</button>`);$('saveTopic').onclick=async()=>{const fd=new FormData($('topicForm')),row=Object.fromEntries(fd.entries());row.sort_order=num(row.sort_order);row.is_active=fd.get('is_active')==='on';row.created_by=t?t.created_by:state.session.user.id;const{error}=await(t?sb.from('os_learning_topics').update(row).eq('id',t.id):sb.from('os_learning_topics').insert(row));if(error)return swalError('บันทึกไม่สำเร็จ',error);closeModal();await loadAll(false);toast('บันทึกหัวข้อแล้ว')};if($('deleteTopic'))$('deleteTopic').onclick=async()=>{if(!confirm('ลบหัวข้อและ Resources ทั้งหมด?'))return;const{error}=await sb.from('os_learning_topics').delete().eq('id',t.id);if(error)return swalError('ลบไม่สำเร็จ',error);closeModal();await loadAll(false);toast('ลบแล้ว')};}
  function openAsset(){openModal('เพิ่ม Learning Resource',`<form id="assetForm" class="form-grid"><label class="aw-label wide">Topic<select class="aw-input" name="topic_id" required><option value="">เลือก</option>${state.learningTopics.map(t=>`<option value="${t.id}">${esc(course(t.course_id)?.name||'')} · ${esc(t.title)}</option>`).join('')}</select></label><label class="aw-label">ประเภท<select class="aw-input" name="asset_type"><option value="video">Video</option><option value="sheet">Sheet</option><option value="link">Link</option><option value="file">File URL</option></select></label><label class="aw-label">ลำดับ<input type="number" class="aw-input" name="sort_order" value="100"></label><label class="aw-label wide">ชื่อ *<input class="aw-input" name="title" required></label><label class="aw-label wide">URL<input class="aw-input" name="url" placeholder="https://..."></label></form>`,`<button class="aw-btn" data-modal-close>ยกเลิก</button><button class="aw-btn primary" id="saveAsset">บันทึก</button>`);$('saveAsset').onclick=async()=>{const row=Object.fromEntries(new FormData($('assetForm')).entries());row.sort_order=num(row.sort_order);const{error}=await sb.from('os_learning_assets').insert(row);if(error)return swalError('บันทึกไม่สำเร็จ',error);closeModal();await loadAll(false);toast('เพิ่ม Resource แล้ว')};}

  function renderTasks(root){const open=state.tasks.filter(x=>!x.completed);root.innerHTML=`<div class="grid-2"><div class="aw-card panel"><div class="panel-head"><div><h3>งานที่ต้องทำ</h3><p>${open.length} งานยังไม่เสร็จ</p></div><button class="aw-btn sky small" id="newTask"><i class="fa-solid fa-plus"></i> เพิ่มงาน</button></div><div class="list">${state.tasks.map(t=>`<div class="list-item"><div class="list-item-head"><div><h4 style="${t.completed?'text-decoration:line-through;color:#94a3b8':''}">${esc(t.task_text)}</h4><p>${t.assigned_student_id?esc(student(t.assigned_student_id)?.display_name||''):''} ${t.due_date?'• due '+date(t.due_date):''}</p></div><span class="status ${t.priority==='urgent'?'red':t.priority==='high'?'amber':'blue'}">${esc(t.priority)}</span></div><div class="module-actions" style="margin-top:8px"><button class="aw-btn small ${t.completed?'':'success'}" data-toggle-task="${t.id}:${!t.completed}">${t.completed?'เปิดใหม่':'เสร็จแล้ว'}</button><button class="aw-btn small danger" data-delete-task="${t.id}">ลบ</button></div></div>`).join('')||'<div class="empty">ไม่มีงาน</div>'}</div></div><div class="aw-card panel"><div class="panel-head"><div><h3>Focus</h3><p>งานเร่งด่วนและกำหนดส่งใกล้ที่สุด</p></div></div>${open.slice().sort((a,b)=>(a.due_date||'9999').localeCompare(b.due_date||'9999')).slice(0,6).map(t=>`<div class="list-item" style="margin-bottom:7px"><h4>${esc(t.task_text)}</h4><p>${t.due_date?date(t.due_date):'ไม่กำหนดวัน'} • ${esc(t.priority)}</p></div>`).join('')||'<div class="empty">เคลียร์หมดแล้ว 🎉</div>'}</div></div>`;$('newTask').onclick=openTask;$$('[data-toggle-task]',root).forEach(b=>b.onclick=async()=>{const[id,val]=b.dataset.toggleTask.split(':');const completed=val==='true';const{error}=await sb.from('os_tasks').update({completed,completed_at:completed?new Date().toISOString():null}).eq('id',id);if(error)return swalError('อัปเดตไม่สำเร็จ',error);await loadAll(false);toast('อัปเดต Task แล้ว')});$$('[data-delete-task]',root).forEach(b=>b.onclick=async()=>{if(!confirm('ลบ Task?'))return;const{error}=await sb.from('os_tasks').delete().eq('id',b.dataset.deleteTask);if(error)return swalError('ลบไม่สำเร็จ',error);await loadAll(false);toast('ลบแล้ว')});}
  function openTask(){openModal('เพิ่ม Task',`<form id="taskForm" class="form-grid"><label class="aw-label wide">งาน *<input class="aw-input" name="task_text" required></label><label class="aw-label">Priority<select class="aw-input" name="priority"><option>normal</option><option>high</option><option>urgent</option><option>low</option></select></label><label class="aw-label">Due date<input type="date" class="aw-input" name="due_date"></label><label class="aw-label wide">นักเรียน<select class="aw-input" name="assigned_student_id"><option value="">ไม่ผูกนักเรียน</option>${state.students.map(s=>`<option value="${s.id}">${esc(s.display_name)}</option>`).join('')}</select></label><label class="aw-label wide">Note<textarea class="aw-input" name="note"></textarea></label></form>`,`<button class="aw-btn" data-modal-close>ยกเลิก</button><button class="aw-btn primary" id="saveTask">เพิ่มงาน</button>`);$('saveTask').onclick=async()=>{const row=Object.fromEntries(new FormData($('taskForm')).entries());row.assigned_student_id=row.assigned_student_id||null;row.due_date=row.due_date||null;row.created_by=state.session.user.id;const{error}=await sb.from('os_tasks').insert(row);if(error)return swalError('เพิ่มงานไม่สำเร็จ',error);closeModal();await loadAll(false);toast('เพิ่ม Task แล้ว')};}

  function renderAnnouncements(root){root.innerHTML=`<div class="aw-card panel"><div class="panel-head"><div><h3>Student Portal Announcements</h3><p>ประกาศสำหรับผู้เรียนและผู้ปกครอง</p></div><button class="aw-btn sky small" id="newAnnouncement"><i class="fa-solid fa-plus"></i> ประกาศ</button></div><div class="grid-3">${state.announcements.map(a=>`<article class="list-item"><div class="list-item-head"><h4>${esc(a.title)}</h4><span class="status ${a.is_active?'green':'red'}">${a.is_active?'active':'off'}</span></div><p>${esc(a.body)}</p><p>เผยแพร่ ${dateTime(a.publish_at)}</p><div class="module-actions"><button class="aw-btn small danger" data-delete-announcement="${a.id}">ลบ</button></div></article>`).join('')||'<div class="empty">ไม่มีประกาศ</div>'}</div></div>`;$('newAnnouncement').onclick=openAnnouncement;$$('[data-delete-announcement]',root).forEach(b=>b.onclick=async()=>{if(!confirm('ลบประกาศ?'))return;const{error}=await sb.from('os_announcements').delete().eq('id',b.dataset.deleteAnnouncement);if(error)return swalError('ลบไม่สำเร็จ',error);await loadAll(false);toast('ลบประกาศแล้ว')});}
  function openAnnouncement(){openModal('เพิ่มประกาศ',`<form id="annForm" class="form-grid"><label class="aw-label wide">หัวข้อ *<input class="aw-input" name="title" required></label><label class="aw-label wide">เนื้อหา *<textarea class="aw-input" name="body" required></textarea></label><label class="aw-label">เริ่มเผยแพร่<input type="datetime-local" class="aw-input" name="publish_at" value="${new Date().toISOString().slice(0,16)}"></label><label class="aw-label">หมดอายุ<input type="datetime-local" class="aw-input" name="expires_at"></label></form>`,`<button class="aw-btn" data-modal-close>ยกเลิก</button><button class="aw-btn primary" id="saveAnn">เผยแพร่</button>`);$('saveAnn').onclick=async()=>{const row=Object.fromEntries(new FormData($('annForm')).entries());row.publish_at=row.publish_at?new Date(row.publish_at).toISOString():new Date().toISOString();row.expires_at=row.expires_at?new Date(row.expires_at).toISOString():null;row.created_by=state.session.user.id;const{error}=await sb.from('os_announcements').insert(row);if(error)return swalError('บันทึกไม่สำเร็จ',error);closeModal();await loadAll(false);toast('เผยแพร่ประกาศแล้ว')};}

  function renderSchedule(root){const dayNames=['จันทร์','อังคาร','พุธ','พฤหัส','ศุกร์','เสาร์','อาทิตย์'];root.innerHTML=`<div class="aw-card panel"><div class="panel-head"><div><h3>ตารางประจำ Tutor</h3><p>อ่านข้อมูลจาก Dynamic Schedule ของระบบ Manager</p></div><a class="aw-btn sky small" href="../manager/?section=schedule"><i class="fa-solid fa-pen"></i> แก้ไขตาราง</a></div><div style="overflow:auto"><div class="calendar-grid">${dayNames.map((d,i)=>{const rows=state.schedules.filter(x=>Number(x.weekday)===i+1&&x.status==='available');return `<div class="day-col"><div class="day-head">${d} · ${rows.length} ช่วง</div>${rows.slice(0,8).map(x=>{const st=state.scheduleTemplates.find(t=>t.id===x.time_template_id);return `<div class="session-chip"><b>${String(st?.start_time||'').slice(0,5)}–${String(st?.end_time||'').slice(0,5)}</b><small>${esc(tutor(x.tutor_id)?.display_name||'')} • cap ${x.capacity}</small></div>`}).join('')}</div>`}).join('')}</div></div></div>`;}

  function renderFinance(el){
    if(!isAdmin()){el.innerHTML=pageHead('Finance','ไม่มีสิทธิ์','ส่วนการเงินเปิดเฉพาะ Admin')+'<div class="section-note danger-note">บัญชี Tutor จะไม่เห็น Payment และ Finance ตามหลัก least privilege</div>';return;}
    const paid=state.payments.filter(x=>x.status==='paid'),pending=state.payments.filter(x=>x.status==='pending'),revenue=state.financeEntries.filter(x=>x.entry_type==='income').reduce((s,x)=>s+num(x.amount),0),expenses=state.financeEntries.filter(x=>x.entry_type==='expense').reduce((s,x)=>s+num(x.amount),0);
    el.innerHTML=pageHead('Finance','การเงิน','Payment จากระบบสมัคร + รายรับ/รายจ่ายของ Tutor OS',`<button class="aw-btn sky" id="newFinance"><i class="fa-solid fa-plus"></i> รายการ Manual</button><a class="aw-btn" href="../manager/?section=payments">ตรวจสลิป</a>`) + `<div class="grid-4">${metric('fa-solid fa-sack-dollar','รายรับรวม',money(revenue),'Tutor OS finance','#dcfce7')}${metric('fa-solid fa-receipt','ชำระแล้ว',paid.length,'Core payments','#e0f2fe')}${metric('fa-solid fa-hourglass-half','รอตรวจ',pending.length,'ต้องดำเนินการ','#fef3c7')}${metric('fa-solid fa-arrow-trend-down','รายจ่าย',money(expenses),'Manual expenses','#ffe4e6')}</div><div class="grid-2" style="margin-top:12px"><div class="aw-card panel"><div class="panel-head"><div><h3>Core Payments</h3><p>ข้อมูลเดียวกับ Manager</p></div></div><div class="list">${state.payments.slice(0,20).map(p=>{const e=state.enrollments.find(x=>x.id===p.enrollment_id);return `<div class="list-item"><div class="list-item-head"><div><h4>${esc(e?.fullname||'ผู้เรียน')}</h4><p>${esc(e?.course_text||'')} • ${money(p.verified_amount||p.amount_submitted)}</p></div><span class="status ${paymentStatusClass(p.status)}">${esc(p.status)}</span></div></div>`}).join('')||'<div class="empty">ไม่มี Payment</div>'}</div></div><div class="aw-card panel"><div class="panel-head"><div><h3>Finance Ledger</h3><p>รวมรายการ Sync และ Manual</p></div></div><div class="list">${state.financeEntries.slice(0,30).map(x=>`<div class="list-item"><div class="list-item-head"><div><h4>${esc(x.description)}</h4><p>${date(x.transaction_date)} ${x.note?'• '+esc(x.note):''}</p></div><b style="color:${x.entry_type==='expense'?'#be123c':'#047857'}">${x.entry_type==='expense'?'-':'+'}${money(x.amount)}</b></div></div>`).join('')||'<div class="empty">ไม่มีรายการ</div>'}</div></div></div>`;
    $('newFinance').onclick=openFinance;
  }
  function openFinance(){openModal('เพิ่มรายการการเงิน',`<form id="financeForm" class="form-grid"><label class="aw-label">ประเภท<select class="aw-input" name="entry_type"><option value="income">รายรับ</option><option value="expense">รายจ่าย</option><option value="refund">คืนเงิน</option><option value="adjustment">ปรับยอด</option></select></label><label class="aw-label">วันที่<input type="date" class="aw-input" name="transaction_date" value="${today()}"></label><label class="aw-label wide">รายละเอียด *<input class="aw-input" name="description" required></label><label class="aw-label">จำนวนเงิน<input type="number" min="0" step="0.01" class="aw-input" name="amount" required></label><label class="aw-label">นักเรียน<select class="aw-input" name="student_id"><option value="">ไม่ผูก</option>${state.students.map(s=>`<option value="${s.id}">${esc(s.display_name)}</option>`).join('')}</select></label><label class="aw-label wide">Note<textarea class="aw-input" name="note"></textarea></label></form>`,`<button class="aw-btn" data-modal-close>ยกเลิก</button><button class="aw-btn primary" id="saveFinance">บันทึก</button>`);$('saveFinance').onclick=async()=>{const row=Object.fromEntries(new FormData($('financeForm')).entries());row.student_id=row.student_id||null;row.amount=num(row.amount);row.created_by=state.session.user.id;const{error}=await sb.from('os_finance_entries').insert(row);if(error)return swalError('บันทึกไม่สำเร็จ',error);closeModal();await loadAll(false);toast('บันทึกรายการแล้ว')};}

  function renderTeam(el){
    const tab=state.subtab.team;
    el.innerHTML=pageHead('People & Content','ทีม & เนื้อหา','ติวเตอร์ สิทธิ์ทีม สมัครงาน Library HR และคำขอวิทยากรเชื่อมกับระบบหลัก',`<a class="aw-btn sky" href="../manager/?section=tutors"><i class="fa-solid fa-users-gear"></i> Manager Tutor</a>`) + tabs('team',[['tutors','ติวเตอร์','fa-solid fa-user-tie'],['staff','Staff & สิทธิ์','fa-solid fa-user-shield'],['library','Library','fa-solid fa-book'],['hr','HR & งานครู','fa-solid fa-briefcase'],['recruitment','Recruitment','fa-solid fa-user-plus']]) + `<div id="teamBody"></div>`;bindTabs(el);const root=$('teamBody');({tutors:renderTutors,staff:renderStaff,library:renderLibrary,hr:renderHR,recruitment:renderRecruitment}[tab]||renderTutors)(root);
  }
  function renderTutors(root){root.innerHTML=`<div class="grid-3">${state.tutors.map(t=>{const courseCount=state.courses.filter(c=>c.tutor_id===t.id).length,studentCount=new Set(state.studentCourses.filter(x=>x.tutor_id===t.id&&x.status==='active').map(x=>x.student_id)).size;return `<article class="aw-card module-card"><div class="person"><div class="avatar">${t.image_url?`<img src="${esc(t.image_url)}" alt="">`:esc(initials(t.display_name))}</div><div><h3>${esc(t.display_name)}</h3><p>${esc(t.role_text||t.full_name||'Tutor')}</p></div></div><p>${courseCount} คอร์ส • ${studentCount} นักเรียน<br>${esc((t.levels||[]).slice(0,3).join(' · '))}</p><div class="module-actions"><a class="aw-btn small" href="../manager/?section=tutors">จัดการ</a><button class="aw-btn small" data-tutor-summary="${t.id}">สรุปงาน</button></div></article>`}).join('')||'<div class="empty">ยังไม่มีติวเตอร์</div>'}</div>`;$$('[data-tutor-summary]',root).forEach(b=>b.onclick=()=>{const t=tutor(b.dataset.tutorSummary),logs=state.teachingLogs.filter(x=>x.tutor_id===t.id),hrs=logs.reduce((s,x)=>s+num(x.hours),0);openModal(t.display_name,`<div class="grid-2"><div class="list-item"><h4>คอร์ส</h4><p>${state.courses.filter(c=>c.tutor_id===t.id).length}</p></div><div class="list-item"><h4>ชั่วโมงบันทึก</h4><p>${hrs} ชม.</p></div></div><div class="list" style="margin-top:10px">${logs.slice(0,10).map(x=>`<div class="list-item"><h4>${esc(x.topic)}</h4><p>${date(x.lesson_date)} • ${num(x.hours)} ชม.</p></div>`).join('')}</div>`,`<button class="aw-btn primary" data-modal-close>ปิด</button>`);});}
  function renderStaff(root){
    if(!isAdmin()){
      const me=state.staffProfiles.find(x=>x.user_id===state.session.user.id)||state.staff;
      root.innerHTML=`<div class="grid-2"><div class="aw-card panel"><div class="panel-head"><div><h3>สิทธิ์ของฉัน</h3><p>Tutor OS staff profile</p></div><span class="status blue">${esc(me?.role||'teacher')}</span></div><div class="list-item"><h4>${esc(me?.display_name||state.session.user.email)}</h4><p>${esc(state.session.user.email||'')}</p></div></div><div class="section-note"><b>การจัดสิทธิ์</b> เปิดเฉพาะ Admin เพื่อป้องกันการยกระดับสิทธิ์โดยไม่ได้รับอนุญาต</div></div>`;
      return;
    }
    root.innerHTML=`<div class="grid-2"><div class="aw-card panel"><div class="panel-head"><div><h3>Staff Directory</h3><p>บัญชีที่เข้า Tutor OS ได้</p></div><button class="aw-btn sky small" id="grantStaff"><i class="fa-solid fa-user-plus"></i> ให้สิทธิ์</button></div><div class="list">${state.staffProfiles.map(x=>`<div class="list-item"><div class="list-item-head"><div><h4>${esc(x.display_name||x.user_id)}</h4><p class="mono-small">${esc(x.user_id)}</p></div><span class="status ${x.is_active?(x.role==='admin'?'violet':'green'):'red'}">${x.is_active?esc(x.role):'disabled'}</span></div><div class="module-actions" style="margin-top:8px"><button class="aw-btn small" data-staff-edit="${x.user_id}">แก้ไข</button>${x.user_id!==state.session.user.id?`<button class="aw-btn small ${x.is_active?'danger':'success'}" data-staff-toggle="${x.user_id}:${!x.is_active}">${x.is_active?'ปิดสิทธิ์':'เปิดสิทธิ์'}</button>`:''}</div></div>`).join('')||'<div class="empty">ยังไม่มี Staff</div>'}</div></div><div class="aw-card panel"><div class="panel-head"><div><h3>Auth → Tutor OS</h3><p>วิธีเพิ่มบัญชีติวเตอร์</p></div></div><div class="section-note"><b>1.</b> สร้าง User ใน Supabase Authentication ก่อน<br><b>2.</b> คัดลอก User UID<br><b>3.</b> กด “ให้สิทธิ์” และเลือก role = teacher/admin<br><br>Manager/Admin ของระบบหลักจะถูก Sync เป็น Tutor OS admin อัตโนมัติ</div><div class="list-item" style="margin-top:10px"><h4>Security</h4><p>Finance, HR และการจัด Staff ถูกบังคับด้วย RLS ฝั่งฐานข้อมูล ไม่ได้อาศัยแค่การซ่อนเมนู</p></div></div></div>`;
    $('grantStaff').onclick=()=>openStaff();
    $$('[data-staff-edit]',root).forEach(b=>b.onclick=()=>openStaff(b.dataset.staffEdit));
    $$('[data-staff-toggle]',root).forEach(b=>b.onclick=async()=>{const[id,val]=b.dataset.staffToggle.split(':');const{error}=await sb.from('os_staff_profiles').update({is_active:val==='true'}).eq('user_id',id);if(error)return swalError('อัปเดตสิทธิ์ไม่สำเร็จ',error);await loadAll(false);toast('อัปเดตสิทธิ์แล้ว')});
  }
  function openStaff(userId=null){
    const x=userId?state.staffProfiles.find(v=>v.user_id===userId):null;
    openModal(x?'แก้ไขสิทธิ์ Staff':'ให้สิทธิ์ Tutor OS',`<form id="staffForm" class="form-grid"><label class="aw-label wide">Supabase Auth User UID *<input class="aw-input" name="user_id" required ${x?'readonly':''} value="${esc(x?.user_id||'')}" placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"></label><label class="aw-label wide">ชื่อที่แสดง<input class="aw-input" name="display_name" value="${esc(x?.display_name||'')}"></label><label class="aw-label">Role<select class="aw-input" name="role"><option value="teacher" ${x?.role==='teacher'?'selected':''}>teacher</option><option value="admin" ${x?.role==='admin'?'selected':''}>admin</option></select></label><label class="aw-label"><span>สถานะ</span><select class="aw-input" name="is_active"><option value="true" ${x?.is_active!==false?'selected':''}>เปิดใช้งาน</option><option value="false" ${x?.is_active===false?'selected':''}>ปิดใช้งาน</option></select></label></form>`,`<button class="aw-btn" data-modal-close>ยกเลิก</button><button class="aw-btn primary" id="saveStaff">บันทึกสิทธิ์</button>`);
    $('saveStaff').onclick=async()=>{const fd=new FormData($('staffForm'));const row={user_id:String(fd.get('user_id')||'').trim(),display_name:String(fd.get('display_name')||'').trim()||null,role:fd.get('role'),is_active:fd.get('is_active')==='true'};if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(row.user_id))return toast('UID ไม่ถูกต้อง','error');const{error}=await sb.from('os_staff_profiles').upsert(row,{onConflict:'user_id'});if(error)return swalError('บันทึกสิทธิ์ไม่สำเร็จ',error);closeModal();await loadAll(false);toast('บันทึกสิทธิ์ Staff แล้ว')};
  }
  function renderLibrary(root){root.innerHTML=`<div class="aw-card panel"><div class="panel-head"><div><h3>Team Library</h3><p>หนังสือ วิดีโอ ชีท ลิงก์ และทรัพยากรสำหรับทีม</p></div><button class="aw-btn sky small" id="addLibrary"><i class="fa-solid fa-plus"></i> เพิ่ม</button></div><div class="grid-3">${state.library.map(x=>`<article class="list-item"><div class="list-item-head"><div><h4>${esc(x.title)}</h4><p>${esc(x.category||'')} • ${esc(x.item_type)}</p></div><span class="status blue">${esc(x.subject_key||'general')}</span></div><p>${esc(x.description||'')}</p><div class="module-actions">${x.url?`<a class="aw-btn small" target="_blank" rel="noopener" href="${esc(x.url)}">เปิด</a>`:''}<button class="aw-btn danger small" data-delete-library="${x.id}">ลบ</button></div></article>`).join('')||'<div class="empty">Library ยังว่าง</div>'}</div></div>`;$('addLibrary').onclick=openLibrary;$$('[data-delete-library]',root).forEach(b=>b.onclick=async()=>{if(!confirm('ลบรายการนี้?'))return;const{error}=await sb.from('os_library_items').delete().eq('id',b.dataset.deleteLibrary);if(error)return swalError('ลบไม่สำเร็จ',error);await loadAll(false);toast('ลบแล้ว')});}
  function openLibrary(){openModal('เพิ่ม Library item',`<form id="libForm" class="form-grid"><label class="aw-label wide">ชื่อ *<input class="aw-input" name="title" required></label><label class="aw-label">หมวด<input class="aw-input" name="category" placeholder="Biology / Teaching"></label><label class="aw-label">Subject key<input class="aw-input" name="subject_key" placeholder="bio"></label><label class="aw-label">ประเภท<select class="aw-input" name="item_type"><option>book</option><option>video</option><option>worksheet</option><option>link</option><option>file</option><option>other</option></select></label><label class="aw-label wide">URL<input class="aw-input" name="url"></label><label class="aw-label wide">รายละเอียด<textarea class="aw-input" name="description"></textarea></label></form>`,`<button class="aw-btn" data-modal-close>ยกเลิก</button><button class="aw-btn primary" id="saveLib">บันทึก</button>`);$('saveLib').onclick=async()=>{const row=Object.fromEntries(new FormData($('libForm')).entries());row.created_by=state.session.user.id;const{error}=await sb.from('os_library_items').insert(row);if(error)return swalError('บันทึกไม่สำเร็จ',error);closeModal();await loadAll(false);toast('เพิ่ม Library แล้ว')};}
  function renderHR(root){if(!isAdmin()){root.innerHTML='<div class="section-note">HR detail เปิดเฉพาะ Admin ส่วน Tutor ใช้หน้าทีมและ Tasks ได้ตามปกติ</div>';return}root.innerHTML=`<div class="grid-2"><div class="aw-card panel"><div class="panel-head"><div><h3>HR entries</h3><p>ค่าตอบแทน ประเมิน Training และบันทึกภายใน</p></div><button class="aw-btn sky small" id="addHR"><i class="fa-solid fa-plus"></i> เพิ่ม</button></div><div class="list">${state.hr.map(x=>`<div class="list-item"><div class="list-item-head"><div><h4>${esc(x.title)}</h4><p>${esc(tutor(x.tutor_id)?.display_name||'')} • ${date(x.entry_date)}</p></div><span class="status violet">${esc(x.entry_type)}</span></div>${x.amount?`<p>${money(x.amount)}</p>`:''}<p>${esc(x.note||'')}</p></div>`).join('')||'<div class="empty">ยังไม่มี HR entry</div>'}</div></div><div class="aw-card panel"><div class="panel-head"><div><h3>Recruitment</h3><p>ใบสมัครติวเตอร์จาก Subweb</p></div></div><div class="metric-value">${state.tutorApplications.length}</div><div class="metric-label">ใบสมัครทั้งหมด</div><div class="module-actions" style="margin-top:12px"><a class="aw-btn" href="../manager/?section=tutorapplications">เปิดระบบรับสมัคร</a><a class="aw-btn" href="../tutor-apply/" target="_blank">ดูหน้าสมัคร</a></div></div></div>`;$('addHR').onclick=openHR;}
  function openHR(){openModal('เพิ่ม HR entry',`<form id="hrForm" class="form-grid"><label class="aw-label wide">ติวเตอร์<select class="aw-input" name="tutor_id"><option value="">เลือก</option>${state.tutors.map(t=>`<option value="${t.id}">${esc(t.display_name)}</option>`).join('')}</select></label><label class="aw-label">ประเภท<select class="aw-input" name="entry_type"><option>note</option><option>compensation</option><option>evaluation</option><option>training</option></select></label><label class="aw-label">วันที่<input type="date" class="aw-input" name="entry_date" value="${today()}"></label><label class="aw-label wide">หัวข้อ *<input class="aw-input" name="title" required></label><label class="aw-label">จำนวนเงิน<input type="number" class="aw-input" name="amount"></label><label class="aw-label wide">Note<textarea class="aw-input" name="note"></textarea></label></form>`,`<button class="aw-btn" data-modal-close>ยกเลิก</button><button class="aw-btn primary" id="saveHR">บันทึก</button>`);$('saveHR').onclick=async()=>{const row=Object.fromEntries(new FormData($('hrForm')).entries());row.tutor_id=row.tutor_id||null;row.amount=row.amount?num(row.amount):null;row.created_by=state.session.user.id;const{error}=await sb.from('os_hr_entries').insert(row);if(error)return swalError('บันทึกไม่สำเร็จ',error);closeModal();await loadAll(false);toast('บันทึก HR แล้ว')};}
  function renderRecruitment(root){root.innerHTML=`<div class="grid-2"><div class="aw-card panel"><div class="panel-head"><div><h3>Tutor Applications</h3><p>เชื่อมกับระบบรับสมัครติวเตอร์ TH/EN</p></div><a class="aw-btn sky small" href="../manager/?section=tutorapplications">จัดการ</a></div><div class="list">${state.tutorApplications.slice(0,15).map(x=>`<div class="list-item"><div class="list-item-head"><div><h4>${esc(`${x.first_name||''} ${x.last_name||''}`.trim())}</h4><p>${esc(x.nickname||'')} • ${esc(x.email||'')}</p></div><span class="status ${x.status==='accepted'?'green':x.status==='rejected'?'red':'amber'}">${esc(x.status)}</span></div></div>`).join('')||'<div class="empty">ไม่มีใบสมัคร</div>'}</div></div><div class="aw-card panel"><div class="panel-head"><div><h3>Speaker Requests</h3><p>คำขอจ้างวิทยากรจากเว็บไซต์หลัก</p></div><a class="aw-btn small" href="../manager/?section=speakers">จัดการ</a></div><div class="list">${state.speakers.slice(0,10).map(x=>`<div class="list-item"><div class="list-item-head"><div><h4>${esc(x.organization)}</h4><p>${esc(x.subject)} • ${esc(x.event_datetime_text)}</p></div><span class="status blue">${esc(x.status)}</span></div></div>`).join('')||'<div class="empty">ไม่มีคำขอ</div>'}</div></div></div>`;}

  function renderReports(el){
    const attTotal=state.attendance.length,attPresent=state.attendance.filter(x=>['present','late'].includes(x.status)).length,attRate=attTotal?Math.round(attPresent/attTotal*100):0;
    const revenue=state.financeEntries.filter(x=>x.entry_type==='income').reduce((s,x)=>s+num(x.amount),0);
    const courseCounts=state.courses.map(c=>({name:c.name,count:new Set(state.studentCourses.filter(x=>x.course_id===c.id&&x.status==='active').map(x=>x.student_id)).size})).sort((a,b)=>b.count-a.count);
    const max=Math.max(1,...courseCounts.map(x=>x.count));
    el.innerHTML=pageHead('Analytics','รายงาน','Executive view จากข้อมูลสมัครเรียน การสอน Attendance และ Finance',`<button class="aw-btn" id="exportReport"><i class="fa-solid fa-file-csv"></i> Export CSV</button>`) + `<div class="grid-4">${metric('fa-solid fa-users','นักเรียน',state.students.filter(x=>!x.archived).length,'ทั้งหมด','#e0f2fe')}${metric('fa-solid fa-percent','Attendance',attRate+'%','มาเรียน + สาย','#dcfce7')}${metric('fa-solid fa-coins','Revenue',isAdmin()?money(revenue):'—','Finance ledger','#fef3c7')}${metric('fa-solid fa-book','Active Courses',state.courses.filter(x=>x.active).length,'Catalog','#ede9fe')}</div><div class="grid-2" style="margin-top:12px"><div class="aw-card panel"><div class="panel-head"><div><h3>นักเรียนต่อคอร์ส</h3><p>อ้างอิง Course UUID เดียวกับ Manager</p></div></div><div class="report-bars">${courseCounts.slice(0,12).map(x=>`<div class="bar-row"><span>${esc(x.name)}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.round(x.count/max*100)}%"></div></div><b>${x.count}</b></div>`).join('')||'<div class="empty">ไม่มีข้อมูล</div>'}</div></div><div class="aw-card panel"><div class="panel-head"><div><h3>Attendance breakdown</h3><p>${attTotal} attendance records</p></div></div>${['present','late','absent','leave'].map(s=>{const n=state.attendance.filter(x=>x.status===s).length,p=attTotal?Math.round(n/attTotal*100):0;return `<div class="bar-row" style="margin-bottom:10px"><span>${s}</span><div class="bar-track"><div class="bar-fill" style="width:${p}%"></div></div><b>${p}%</b></div>`}).join('')}</div></div>`;
    $('exportReport').onclick=exportReport;
  }
  function exportReport(){const rows=[['metric','value'],['students',state.students.length],['active_courses',state.courses.filter(x=>x.active).length],['attendance_records',state.attendance.length],['finance_entries',state.financeEntries.length],['tasks_open',state.tasks.filter(x=>!x.completed).length],[],['course','active_students'],...state.courses.map(c=>[c.name,new Set(state.studentCourses.filter(x=>x.course_id===c.id&&x.status==='active').map(x=>x.student_id)).size])];downloadCSV('arewarin-tutor-os-report.csv',rows);}

  function renderSettings(el){
    const tab=state.subtab.settings;
    el.innerHTML=pageHead('System','ตั้งค่า & เครื่องมือ','Connection health, Quick Replies, Import และทางลัดไปยังระบบที่เชื่อมกัน',`<button class="aw-btn" id="refreshSettings"><i class="fa-solid fa-rotate"></i> ตรวจอีกครั้ง</button>`) + tabs('settings',[['health','System Health','fa-solid fa-heart-pulse'],['quick','Quick Replies','fa-solid fa-message'],['import','Import CSV','fa-solid fa-file-import'],['links','Connected Apps','fa-solid fa-link']]) + `<div id="settingsBody"></div>`;bindTabs(el);$('refreshSettings').onclick=()=>loadAll();const root=$('settingsBody');({health:renderHealth,quick:renderQuick,import:renderImport,links:renderLinks}[tab]||renderHealth)(root);
  }
  function renderHealth(root){root.innerHTML=`<div class="grid-2"><div class="aw-card panel"><div class="panel-head"><div><h3>Supabase Connection</h3><p>${esc(cfg.SUPABASE_URL)}</p></div><span class="status ${state.systemReady?'green':'amber'}">${state.systemReady?'READY':'UPGRADE'}</span></div><div class="list-item"><h4>Authentication</h4><p>${esc(state.session?.user?.email||'')}</p></div><div class="list-item"><h4>Tutor OS Role</h4><p>${esc(state.staff?.role||'')}</p></div><div class="list-item"><h4>OS Schema</h4><p>${state.systemReady?'พบตาราง Tutor OS extension แล้ว':'ยังไม่พร้อม — รัน TUTOR_OS_V14_UPGRADE.sql'}</p></div></div><div class="aw-card panel"><div class="panel-head"><div><h3>Diagnostics</h3><p>ข้อผิดพลาดจากการ Sync รอบล่าสุด</p></div></div><div class="list">${state.errors.map(e=>`<div class="list-item"><p>${esc(e)}</p></div>`).join('')||'<div class="section-note"><b>ผ่าน</b> — ไม่พบข้อผิดพลาดในการโหลดข้อมูลรอบล่าสุด</div>'}</div></div></div>`;}
  function renderQuick(root){root.innerHTML=`<div class="grid-2"><div class="aw-card panel"><div class="panel-head"><div><h3>Quick Replies</h3><p>ข้อความที่ทีมใช้บ่อย</p></div><button class="aw-btn sky small" id="addQuick"><i class="fa-solid fa-plus"></i> เพิ่ม</button></div><div class="list">${state.quickReplies.map(x=>`<div class="list-item"><div class="list-item-head"><div><h4>${esc(x.title)}</h4><p>${esc(x.message_text)}</p></div><button class="aw-btn small" data-copy-quick="${x.id}">คัดลอก</button></div></div>`).join('')||'<div class="empty">ยังไม่มี Quick Reply</div>'}</div></div><div class="aw-card panel"><div class="panel-head"><div><h3>Tips</h3><p>ใช้ Quick Replies สำหรับ LINE / โทรติดตาม / นัดเรียน</p></div></div><div class="section-note">ข้อความเก็บใน Supabase และใช้ร่วมกันได้ทุกบัญชี Staff ที่มีสิทธิ์ Tutor OS</div></div></div>`;$('addQuick').onclick=openQuick;$$('[data-copy-quick]',root).forEach(b=>b.onclick=async()=>{const x=state.quickReplies.find(v=>v.id===b.dataset.copyQuick);await navigator.clipboard.writeText(x.message_text);toast('คัดลอกแล้ว')});}
  function openQuick(){openModal('เพิ่ม Quick Reply',`<form id="quickForm" class="form-grid"><label class="aw-label wide">ชื่อ *<input class="aw-input" name="title" required></label><label class="aw-label wide">ข้อความ *<textarea class="aw-input" name="message_text" required></textarea></label><label class="aw-label">ลำดับ<input type="number" class="aw-input" name="sort_order" value="100"></label></form>`,`<button class="aw-btn" data-modal-close>ยกเลิก</button><button class="aw-btn primary" id="saveQuick">บันทึก</button>`);$('saveQuick').onclick=async()=>{const row=Object.fromEntries(new FormData($('quickForm')).entries());row.sort_order=num(row.sort_order);const{error}=await sb.from('os_quick_replies').insert(row);if(error)return swalError('บันทึกไม่สำเร็จ',error);closeModal();await loadAll(false);toast('เพิ่ม Quick Reply แล้ว')};}
  function renderImport(root){root.innerHTML=`<div class="grid-2"><div class="aw-card panel"><div class="panel-head"><div><h3>Import CRM CSV</h3><p>รองรับ name, phone, email, line_id, guardian_name, guardian_phone, stage, source, notes</p></div></div><div class="file-card"><input id="crmCsv" type="file" accept=".csv,text/csv" class="aw-input"><div class="module-actions" style="margin-top:10px"><button class="aw-btn sky" id="importCrmCsv"><i class="fa-solid fa-file-import"></i> นำเข้า</button><button class="aw-btn" id="downloadCrmTemplate">Template CSV</button></div></div></div><div class="aw-card panel"><div class="panel-head"><div><h3>Advanced Tools</h3><p>ข้อมูล Course / Tutor / Enrollment ให้จัดการผ่าน Manager เพื่อรักษา single source of truth</p></div></div><div class="section-note"><b>หลักการ:</b> Tutor OS นำเข้าข้อมูลเฉพาะ Operational/CRM ส่วนข้อมูลธุรกรรมหลักไม่สร้างซ้ำ</div><div class="module-actions" style="margin-top:12px"><a class="aw-btn" href="../manager/?section=enrollments">Enrollment</a><a class="aw-btn" href="../manager/?section=tutors">Tutors</a><a class="aw-btn" href="../manager/?section=courses">Courses</a></div></div></div>`;$('downloadCrmTemplate').onclick=()=>downloadCSV('arewarin-crm-template.csv',[['name','phone','email','line_id','guardian_name','guardian_phone','stage','source','notes'],['น้องตัวอย่าง','08xxxxxxxx','student@example.com','lineid','คุณแม่','08xxxxxxxx','lead','Facebook','สนใจ A-Level Biology']]);$('importCrmCsv').onclick=importCRMCSV;}
  async function importCRMCSV(){const f=$('crmCsv').files[0];if(!f)return toast('กรุณาเลือกไฟล์','error');const rows=parseCSV(await f.text());if(!rows.length)return toast('ไม่พบข้อมูล','error');const allowed=['name','phone','email','line_id','guardian_name','guardian_phone','stage','source','notes'];const data=rows.map(r=>Object.fromEntries(allowed.map(k=>[k,r[k]??null]))).filter(r=>r.name);const{error}=await sb.from('os_crm_contacts').insert(data);if(error)return swalError('นำเข้าไม่สำเร็จ',error);await loadAll(false);toast(`นำเข้า ${data.length} รายการแล้ว`);}
  function renderLinks(root){root.innerHTML=`<div class="grid-3">${connectedCard('fa-solid fa-table-cells-large','AreWarin Manager','Catalog, Tutor, Schedule, Payment, Policies, Branding','../manager/','เปิด Manager')}${connectedCard('fa-solid fa-graduation-cap','Student Enrollment','หน้าเว็บสมัครเรียนหลักและต่อคอร์สนักเรียนเดิม','../','เปิดเว็บสมัคร')}${connectedCard('fa-solid fa-user-plus','Tutor Recruitment','ระบบสมัครติวเตอร์ TH/EN และเอกสารประกอบ','../tutor-apply/','เปิดหน้าสมัคร')}${connectedCard('fa-regular fa-comment-dots','Reviews','Subweb รีวิวและ Social proof','../reviews/','เปิดรีวิว')}${connectedCard('fa-solid fa-microphone','Speaker Requests','คำขอจ้างวิทยากรและติดตามสถานะ','../manager/?section=speakers','จัดการ')}${connectedCard('fa-solid fa-file-contract','Policy CMS','กติกาสมัครเรียนและสมัครติวเตอร์ TH/EN','../manager/?section=policies','แก้นโยบาย')}</div>`;}

  function openModal(title,body,actions='<button class="aw-btn primary" data-modal-close>ปิด</button>'){
    $('modalRoot').innerHTML=`<div class="modal-backdrop" id="modalBackdrop"><section class="modal"><header class="modal-head"><h3>${esc(title)}</h3><button class="aw-btn small" data-modal-close><i class="fa-solid fa-xmark"></i></button></header><div class="modal-body">${body}</div><footer class="modal-actions">${actions}</footer></section></div>`;
    $$('[data-modal-close]',$('modalRoot')).forEach(b=>b.onclick=closeModal);$('modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};
  }
  function closeModal(){ $('modalRoot').innerHTML=''; }

  function parseCSV(text){
    const lines=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];
    const parseLine=line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===','&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out};
    const head=parseLine(lines[0]).map(x=>x.trim());return lines.slice(1).map(line=>{const vals=parseLine(line);return Object.fromEntries(head.map((h,i)=>[h,vals[i]?.trim()??'']))});
  }
  function downloadCSV(filename,rows){const csv='\uFEFF'+rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=filename;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0);}

  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('modalBackdrop'))closeModal();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();activateSection('students');setTimeout(()=>$('studentSearch')?.focus(),50)}});
  sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){state.session=null;showLogin();}});

  boot();
})();
