(()=>{
'use strict';
const sb=window.AreWarinAPI?.sb;if(!sb)return;
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:0}).format(Number(v||0));
const dt=v=>v?new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
const V={tab:'action',students:[],courses:[],tutors:[],groups:[],reschedules:[],assignments:[],subs:[],tickets:[],parents:[],certs:[],rules:[],devices:[],permissions:[],audit:[],action:{},aging:{},health:null,student360:null,studentId:null};
async function q(p,fallback=[]){try{const{data,error}=await p;if(error)throw error;return data??fallback}catch(e){console.warn('[V17]',e);return fallback}}
async function rpc(name,args={},fallback=null){try{const{data,error}=await sb.rpc(name,args);if(error)throw error;return data}catch(e){console.warn('[V17 RPC]',name,e);return fallback}}
function toast(m,err=false){window.Swal?Swal.fire({icon:err?'error':'success',title:m,confirmButtonColor:'#0ea5e9'}):alert(m)}
function nav(section){const b=document.querySelector(`.nav[data-section="${section}"]`);if(b)b.click()}
function metric(icon,label,val,note,tone='sky'){return `<article class="v17-metric ${tone}"><span>${icon}</span><div><small>${label}</small><b>${val}</b><em>${note}</em></div></article>`}
async function load(){const results=await Promise.all([
 q(sb.from('os_students').select('*').eq('archived',false).order('display_name')),
 q(sb.from('courses').select('id,name,active').order('name')),
 q(sb.from('tutors').select('id,display_name,active').order('display_name')),
 q(sb.from('os_student_groups').select('*').order('name')),
 q(sb.from('student_reschedule_requests').select('*').order('created_at',{ascending:false})),
 q(sb.from('student_assignments').select('*').order('created_at',{ascending:false})),
 q(sb.from('student_assignment_submissions').select('*').order('submitted_at',{ascending:false})),
 q(sb.from('student_support_tickets').select('*').order('updated_at',{ascending:false})),
 q(sb.from('student_parent_links').select('id,student_id,parent_name,relationship,active,last_used_at,created_at').order('created_at',{ascending:false})),
 q(sb.from('student_certificates').select('*').order('issued_at',{ascending:false})),
 q(sb.from('student_notification_rules').select('*').order('rule_key')),
 q(sb.from('student_devices').select('*').order('last_seen_at',{ascending:false}).limit(500)),
 q(sb.from('aw_role_permissions').select('*').order('role_key').order('module_key')),
 q(sb.from('aw_audit_log').select('*').order('created_at',{ascending:false}).limit(200))
 ]);
 ['students','courses','tutors','groups','reschedules','assignments','subs','tickets','parents','certs','rules','devices','permissions','audit'].forEach((k,i)=>V[k]=results[i]);
 V.action=await rpc('aw_v17_action_center',{},{} )||{};V.aging=await rpc('aw_v17_finance_aging',{},{} )||{};V.health=await rpc('aw_v17_system_health',{},null);
 renderControl();renderStudent360();renderGovernance();updateSearchButton();
}
function updateSearchButton(){const b=$('v17SearchBtn');if(b)b.innerHTML='<i class="fas fa-magnifying-glass"></i><span class="top-label">ค้นหาทั้งระบบ</span><kbd>⌘K</kbd>'}
function renderControl(){const root=$('v17ControlRoot');if(!root)return;const a=V.action||{}, tabs=[['action','Action Center'],['services','Student Services'],['finance','Finance Center'],['groups','Group Locker'],['recruit','Tutor Pipeline']];root.innerHTML=`<div class="v17-tabs">${tabs.map(x=>`<button data-v17tab="${x[0]}" class="${V.tab===x[0]?'active':''}">${x[1]}</button>`).join('')}</div><div id="v17ControlBody"></div>`;root.querySelectorAll('[data-v17tab]').forEach(b=>b.onclick=()=>{V.tab=b.dataset.v17tab;renderControl()});const body=$('v17ControlBody');({action:renderAction,services:renderServices,finance:renderFinance,groups:renderGroups,recruit:renderRecruit}[V.tab]||renderAction)(body)}
function renderAction(root){const a=V.action||{};root.innerHTML=`<div class="v17-metrics">${metric('฿','รอตรวจชำระ',a.pending_payments||0,'Payment','amber')}${metric('◫','ขอเลื่อนเรียน',a.pending_reschedules||0,'รออนุมัติ','sky')}${metric('✓','การบ้านรอตรวจ',a.homework_to_grade||0,'Submissions','indigo')}${metric('?','Ticket เปิด',a.open_tickets||0,`${a.urgent_tickets||0} เร่งด่วน`,'rose')}${metric('◷','ใกล้หมดชั่วโมง',a.low_hours||0,'ควรเตรียมต่อคอร์ส','emerald')}${metric('+','สมัครติวเตอร์ใหม่',a.new_tutor_apps||0,'Recruitment','violet')}</div><div class="v17-grid"><article class="v17-card"><div class="v17-head"><div><small>TODAY</small><h3>สิ่งที่ต้องทำวันนี้</h3></div><b>${a.today_sessions||0} คาบ</b></div>${actionRow('ตรวจการชำระเงิน',a.pending_payments,'payments','fa-wallet')}${actionRow('คำขอเลื่อน/ชดเชย',a.pending_reschedules,null,'fa-calendar')}${actionRow('ตรวจการบ้าน',a.homework_to_grade,null,'fa-file-pen')}${actionRow('Support Ticket',a.open_tickets,null,'fa-headset')}${actionRow('นักเรียนใกล้หมดชั่วโมง',a.low_hours,'student360','fa-hourglass-half')}</article><article class="v17-card"><div class="v17-head"><div><small>AUTOMATION</small><h3>ระบบอัตโนมัติ</h3></div><span class="v17-chip green">V17</span></div><div class="v17-note">Active Course จะถือเป็นสถานะธุรกรรมที่เสร็จแล้ว · Student Portal ซ่อนยอดเก่า · Low hours ส่งเข้าสู่ Renewal flow · ทุกการเปลี่ยนแปลงสำคัญถูกบันทึก Audit Log</div><div class="v17-health-mini"><span>นักเรียน Active <b>${a.active_students||0}</b></span><span>ผ่อนเกินกำหนด <b>${a.overdue_installments||0}</b></span><span>Ticket ด่วน <b>${a.urgent_tickets||0}</b></span></div></article></div>`;root.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>nav(b.dataset.route))}
function actionRow(label,count,route,icon){return `<button class="v17-action-row" ${route?`data-route="${route}"`:''}><i class="fas ${icon}"></i><span>${label}</span><b>${count||0}</b><em>›</em></button>`}
function renderServices(root){const pending=V.reschedules.filter(x=>x.status==='pending'), grade=V.subs.filter(x=>x.status==='submitted'), tickets=V.tickets.filter(x=>!['resolved','closed'].includes(x.status));root.innerHTML=`<div class="v17-grid"><article class="v17-card"><div class="v17-head"><div><small>SCHEDULE</small><h3>คำขอเลื่อนเรียน</h3></div><span class="v17-chip">${pending.length}</span></div>${V.reschedules.slice(0,10).map(r=>`<div class="v17-list"><div><b>${esc(student(r.student_id)?.display_name||'นักเรียน')}</b><p>${dt(r.requested_start_at)} · ${esc(r.reason||'')}</p></div><span class="v17-chip ${r.status==='approved'?'green':r.status==='rejected'?'red':''}">${esc(r.status)}</span>${r.status==='pending'?`<div class="v17-inline"><button data-res-ok="${r.id}">อนุมัติ</button><button class="danger" data-res-no="${r.id}">ปฏิเสธ</button></div>`:''}</div>`).join('')||'<div class="v17-empty">ไม่มีคำขอ</div>'}</article><article class="v17-card"><div class="v17-head"><div><small>HOMEWORK</small><h3>งานรอตรวจ</h3></div><span class="v17-chip">${grade.length}</span></div>${grade.slice(0,10).map(s=>{const as=V.assignments.find(a=>a.id===s.assignment_id);return `<div class="v17-list"><div><b>${esc(student(s.student_id)?.display_name||'')}</b><p>${esc(as?.title||'การบ้าน')} · ${dt(s.submitted_at)}</p></div><button data-grade="${s.id}">ตรวจงาน</button></div>`}).join('')||'<div class="v17-empty">ไม่มีงานรอตรวจ</div>'}</article><article class="v17-card v17-wide"><div class="v17-head"><div><small>SUPPORT</small><h3>Ticket ล่าสุด</h3></div><span class="v17-chip ${tickets.some(x=>x.priority==='urgent')?'red':''}">${tickets.length} เปิดอยู่</span></div><div class="v17-table"><table><thead><tr><th>Ticket</th><th>นักเรียน</th><th>ประเภท</th><th>หัวข้อ</th><th>สถานะ</th><th></th></tr></thead><tbody>${V.tickets.slice(0,20).map(t=>`<tr><td>${esc(t.ticket_no||'')}</td><td>${esc(student(t.student_id)?.display_name||'')}</td><td>${esc(t.category)}</td><td>${esc(t.subject)}</td><td><span class="v17-chip">${esc(t.status)}</span></td><td><button data-ticket="${t.id}">ตอบ/จัดการ</button></td></tr>`).join('')}</tbody></table></div></article></div>`;bindServices(root)}
function bindServices(root){root.querySelectorAll('[data-res-no]').forEach(b=>b.onclick=async()=>{await sb.from('student_reschedule_requests').update({status:'rejected',reviewed_at:new Date().toISOString()}).eq('id',b.dataset.resNo);await load()});root.querySelectorAll('[data-res-ok]').forEach(b=>b.onclick=async()=>{const r=V.reschedules.find(x=>x.id===b.dataset.resOk);if(!r)return;await sb.from('student_reschedule_requests').update({status:'approved',reviewed_at:new Date().toISOString()}).eq('id',r.id);await load()});root.querySelectorAll('[data-grade]').forEach(b=>b.onclick=async()=>{const score=prompt('คะแนน');if(score===null)return;const feedback=prompt('Feedback','')||'';await sb.from('student_assignment_submissions').update({score:Number(score),feedback,status:'graded',graded_at:new Date().toISOString()}).eq('id',b.dataset.grade);await load()});root.querySelectorAll('[data-ticket]').forEach(b=>b.onclick=async()=>{const t=V.tickets.find(x=>x.id===b.dataset.ticket),msg=prompt(`${t?.ticket_no||'Ticket'} — ข้อความตอบกลับ`);if(!msg)return;const u=(await sb.auth.getUser()).data.user;await sb.from('student_support_messages').insert({ticket_id:b.dataset.ticket,sender_user_id:u?.id,sender_type:'staff',message:msg});await sb.from('student_support_tickets').update({status:'waiting_student'}).eq('id',b.dataset.ticket);await load()})}
function renderFinance(root){const a=V.aging||{};root.innerHTML=`<div class="v17-metrics">${metric('7','ค้าง 1–7 วัน',money(a.current),'ยอด Pending','amber')}${metric('30','ค้าง 8–30 วัน',money(a.d8_30),'ควรติดตาม','rose')}${metric('+','ค้าง >30 วัน',money(a.over30),'ต้องตรวจสอบ','rose')}${metric('✓','รับเงิน 30 วัน',money(a.paid_30d),`${a.pending_count||0} รายการค้าง`,'emerald')}</div><article class="v17-card"><div class="v17-head"><div><small>FINANCE FLOW</small><h3>ศูนย์กลางการเงิน</h3></div><button data-open-pay>เปิดหน้าการชำระเงินหลัก</button></div><div class="v17-note">V17 ไม่สร้าง Payment ซ้ำ แต่คำนวณ Aging จากตาราง payments เดิม และ Audit การเปลี่ยนสถานะทุกครั้ง</div></article>`;root.querySelector('[data-open-pay]').onclick=()=>nav('payments')}
function renderGroups(root){root.innerHTML=`<div class="v17-grid"><article class="v17-card"><div class="v17-head"><div><small>GROUP LOCKER</small><h3>กลุ่มเรียน</h3></div><span class="v17-chip green">${V.groups.filter(x=>x.status==='active').length} Active</span></div>${V.groups.slice(0,15).map(g=>`<div class="v17-list"><div><b>${esc(g.group_code)} · ${esc(g.name)}</b><p>${esc(course(g.course_id)?.name||'')} · ${esc(g.mode||'')}</p></div><button data-broadcast="${g.id}">ประกาศ</button></div>`).join('')}</article><article class="v17-card"><div class="v17-head"><div><small>WORKFLOW</small><h3>Group Operations</h3></div></div><div class="v17-note">การเช็กชื่อและตัดชั่วโมงยังใช้ Group Locker ใน Tutor OS เป็นแหล่งเดียว V17 เพิ่ม Broadcast ให้สื่อสารกับนักเรียน/ผู้ปกครองโดยไม่สร้างกลุ่มซ้ำ</div><button data-open-groups class="v17-primary">เปิด Group Locker ใน Tutor OS</button></article></div>`;root.querySelector('[data-open-groups]').onclick=()=>location.href='../tutor-os/?section=groups';root.querySelectorAll('[data-broadcast]').forEach(b=>b.onclick=async()=>{const title=prompt('หัวข้อประกาศ');if(!title)return;const body=prompt('ข้อความ');if(!body)return;const u=(await sb.auth.getUser()).data.user;const{error}=await sb.from('os_group_broadcasts').insert({group_id:b.dataset.broadcast,title,body,created_by:u?.id});if(error)return toast(error.message,true);toast('ส่งประกาศแล้ว')})}
function renderRecruit(root){root.innerHTML=`<article class="v17-card"><div class="v17-head"><div><small>RECRUITMENT PIPELINE</small><h3>ผู้สมัครติวเตอร์</h3></div><button data-open-apps>เปิดหน้าหลัก</button></div><div class="v17-pipeline">${['new','review','interview','demo','accepted','onboarding','active'].map(stage=>`<div><small>${stage}</small><b>${(window.state?.tutorApplications||[]).filter(x=>(x.pipeline_stage||x.status)===stage).length}</b></div>`).join('')}</div><div class="v17-note">Pipeline ใหม่: New → Review → Interview → Demo Teaching → Accepted → Onboarding → Active Tutor</div></article>`;root.querySelector('[data-open-apps]').onclick=()=>nav('tutorapplications')}
function student(id){return V.students.find(x=>x.id===id)}function course(id){return V.courses.find(x=>x.id===id)}
function renderStudent360(){const root=$('v17Student360Root');if(!root)return;root.innerHTML=`<div class="v17-student-search"><input id="v17StudentQuery" placeholder="ค้นหาชื่อ เบอร์ หรือ Student ID"><button id="v17StudentFind">ค้นหา</button></div><div id="v17StudentList"></div><div id="v17StudentDetail"></div>`;const find=()=>{const qv=$('v17StudentQuery').value.trim().toLowerCase();const rows=V.students.filter(s=>!qv||[s.display_name,s.first_name,s.last_name,s.phone,s.student_code].some(v=>String(v||'').toLowerCase().includes(qv))).slice(0,20);$('v17StudentList').innerHTML=rows.map(s=>`<button class="v17-student-row" data-student="${s.id}"><span>${esc((s.nickname||s.first_name||'A').slice(0,1))}</span><div><b>${esc(s.display_name||`${s.first_name||''} ${s.last_name||''}`)}</b><small>${esc(s.student_code||'')} · ${esc(s.phone||'')} · ${esc(s.school||'')}</small></div><em>เปิด 360°</em></button>`).join('')||'<div class="v17-empty">ไม่พบข้อมูล</div>';root.querySelectorAll('[data-student]').forEach(b=>b.onclick=()=>open360(b.dataset.student))};$('v17StudentFind').onclick=find;$('v17StudentQuery').oninput=find;find();if(V.studentId)open360(V.studentId)}
async function open360(id){V.studentId=id;V.student360=await rpc('aw_v17_student_360',{p_student_id:id},null);const d=$('v17StudentDetail');if(!V.student360){d.innerHTML='<div class="v17-card v17-note">Student 360 ต้องรัน V17 SQL ก่อน</div>';return}const x=V.student360,s=x.student||{},pools=x.hour_pools||[],courses=x.courses||[];d.innerHTML=`<article class="v17-360hero"><div><small>STUDENT 360°</small><h2>${esc(s.display_name||`${s.first_name||''} ${s.last_name||''}`)}</h2><p>${esc(s.student_code||'')} · ${esc(s.phone||'')} · ${esc(s.school||'')} · ${esc(s.grade||'')}</p></div><span>${esc(s.status||'active')}</span></article><div class="v17-metrics">${metric('▤','คอร์ส',courses.length,'ประวัติทั้งหมด','sky')}${metric('◷','ชั่วโมงคงเหลือ',pools.some(p=>p.unlimited)?'∞':pools.reduce((a,p)=>a+Math.max(0,Number(p.total_hours||0)-Number(p.used_hours||0)),0).toFixed(1),'Hour Wallet','emerald')}${metric('✓','Attendance',(x.attendance||[]).length,'ประวัติ','indigo')}${metric('?','Tickets',(x.tickets||[]).filter(t=>!['resolved','closed'].includes(t.status)).length,'เปิดอยู่','amber')}</div><div class="v17-360tabs">${['courses','hours','schedule','payment','homework','support','parent','timeline'].map(t=>`<button data-360="${t}">${t}</button>`).join('')}</div><div id="v17_360body"></div>`;d.querySelectorAll('[data-360]').forEach(b=>b.onclick=()=>render360Tab(b.dataset['360']));render360Tab('courses')}
function render360Tab(tab){const x=V.student360,root=$('v17_360body');if(!root)return;const tables={courses:()=>`<div class="v17-table"><table><thead><tr><th>คอร์ส</th><th>สถานะ</th><th>ชั่วโมง</th><th>ราคา</th></tr></thead><tbody>${(x.courses||[]).map(c=>`<tr><td>${esc(c.course_label||course(c.course_id)?.name||'')}</td><td>${esc(c.status)}</td><td>${Number(c.hours_used||0).toFixed(1)} / ${Number(c.hours_total||0).toFixed(1)}</td><td>${money(c.price)}</td></tr>`).join('')}</tbody></table></div>`,hours:()=>`<div class="v17-table"><table><thead><tr><th>เวลา</th><th>ประเภท</th><th>ชม.</th><th>หมายเหตุ</th></tr></thead><tbody>${(x.hour_ledger||[]).map(h=>`<tr><td>${dt(h.created_at)}</td><td>${esc(h.entry_type)}</td><td>${Number(h.hours_delta||0).toFixed(2)}</td><td>${esc(h.note||'')}</td></tr>`).join('')}</tbody></table></div>`,schedule:()=>cards(x.schedule,'title','start_at'),payment:()=>cards(x.payments,'status','created_at'),homework:()=>cards(x.assignments,'title','due_at'),support:()=>cards(x.tickets,'subject','updated_at'),parent:()=>cards(x.parent_links,'parent_name','last_used_at'),timeline:()=>{const rows=[...(x.hour_ledger||[]).map(v=>({at:v.created_at,title:`Hour ${v.entry_type}`,sub:`${v.hours_delta} ชม. ${v.note||''}`})),...(x.tickets||[]).map(v=>({at:v.updated_at,title:v.ticket_no||'Ticket',sub:`${v.subject} · ${v.status}`})),...(x.schedule||[]).map(v=>({at:v.start_at,title:v.title||'คาบเรียน',sub:v.status}))].sort((a,b)=>new Date(b.at)-new Date(a.at)).slice(0,50);return `<div class="v17-timeline">${rows.map(r=>`<div><time>${dt(r.at)}</time><b>${esc(r.title)}</b><p>${esc(r.sub||'')}</p></div>`).join('')}</div>`}};root.innerHTML=(tables[tab]||tables.courses)()}
function cards(rows,title,dateKey){return `<div class="v17-cards">${(rows||[]).slice(0,30).map(x=>`<article><b>${esc(x[title]||'รายการ')}</b><p>${dt(x[dateKey])}</p><small>${esc(x.status||x.relationship||'')}</small></article>`).join('')||'<div class="v17-empty">ไม่มีข้อมูล</div>'}</div>`}
function renderGovernance(){const root=$('v17GovernanceRoot');if(!root)return;const h=V.health||{},issues=h.issues||[];root.innerHTML=`<div class="v17-grid"><article class="v17-card"><div class="v17-head"><div><small>SYSTEM HEALTH</small><h3>Data Integrity Monitor</h3></div><span class="v17-chip ${Number(h.summary?.issue_total||0)===0?'green':'red'}">${h.summary?.issue_total??'—'} issues</span></div>${issues.map(i=>`<div class="v17-health-row"><span class="${Number(i.total)>0?'bad':'ok'}"></span><div><b>${esc(i.title)}</b><p>${esc(i.code)}</p></div><strong>${i.total}</strong></div>`).join('')||'<div class="v17-note">รัน V17 SQL เพื่อเปิด System Health</div>'}</article><article class="v17-card"><div class="v17-head"><div><small>PERMISSIONS</small><h3>Role Matrix</h3></div><span class="v17-chip">${V.permissions.length}</span></div><div class="v17-table"><table><thead><tr><th>Role</th><th>Module</th><th>View</th><th>Create</th><th>Update</th><th>Delete</th></tr></thead><tbody>${V.permissions.map(p=>`<tr><td>${esc(p.role_key)}</td><td>${esc(p.module_key)}</td><td>${yes(p.can_view)}</td><td>${yes(p.can_create)}</td><td>${yes(p.can_update)}</td><td>${yes(p.can_delete)}</td></tr>`).join('')}</tbody></table></div></article><article class="v17-card v17-wide"><div class="v17-head"><div><small>AUDIT LOG</small><h3>การเปลี่ยนแปลงล่าสุด</h3></div><span class="v17-chip">${V.audit.length}</span></div><div class="v17-table"><table><thead><tr><th>เวลา</th><th>ผู้ทำ</th><th>Action</th><th>Table</th><th>Record</th></tr></thead><tbody>${V.audit.slice(0,100).map(a=>`<tr><td>${dt(a.created_at)}</td><td>${esc(a.actor_role||'system')}</td><td>${esc(a.action)}</td><td>${esc(a.table_name)}</td><td>${esc(a.record_id||'')}</td></tr>`).join('')}</tbody></table></div></article></div>`}
function yes(v){return v?'<span class="v17-yes">✓</span>':'—'}
function installSearch(){const actions=document.querySelector('.manager-topbar .flex.gap-2.items-center');if(actions&&!$('v17SearchBtn')){const b=document.createElement('button');b.id='v17SearchBtn';b.className='top-action bg-white border-slate-200 text-slate-600 hover:border-sky-200 hover:text-sky-600';b.onclick=openSearch;actions.prepend(b)}document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}})}
async function openSearch(){let box=$('v17Palette');if(!box){box=document.createElement('div');box.id='v17Palette';box.innerHTML='<div class="v17-palette"><div class="v17-palette-head"><i class="fas fa-magnifying-glass"></i><input id="v17GlobalQuery" autocomplete="off" placeholder="ค้นหา ชื่อ เบอร์ Student ID Receipt Course Tutor Ticket..."><kbd>ESC</kbd></div><div id="v17SearchResults" class="v17-search-results"><div class="v17-empty">พิมพ์อย่างน้อย 2 ตัวอักษร</div></div></div>';document.body.append(box);box.onclick=e=>{if(e.target===box)box.remove()};document.addEventListener('keydown',e=>{if(e.key==='Escape')box?.remove()},{once:true});$('v17GlobalQuery').oninput=async e=>{const qv=e.target.value.trim(),root=$('v17SearchResults');if(qv.length<2){root.innerHTML='<div class="v17-empty">พิมพ์อย่างน้อย 2 ตัวอักษร</div>';return}const rows=await rpc('aw_v17_search',{p_query:qv},[])||[];root.innerHTML=rows.map(r=>`<button data-search-kind="${r.kind}" data-search-id="${r.id}" data-search-route="${r.route}"><span>${esc(r.kind)}</span><div><b>${esc(r.title)}</b><small>${esc(r.subtitle||'')}</small></div><em>›</em></button>`).join('')||'<div class="v17-empty">ไม่พบข้อมูล</div>';root.querySelectorAll('[data-search-kind]').forEach(b=>b.onclick=()=>{const route=b.dataset.searchRoute;if(b.dataset.searchKind==='student'){V.studentId=b.dataset.searchId;box.remove();nav('student360');setTimeout(()=>open360(V.studentId),150)}else{box.remove();nav(route)}})}};setTimeout(()=>$('v17GlobalQuery').focus(),30)}
function init(){installSearch();load();setInterval(()=>{if(!$('app')?.classList.contains('hidden'))load()},60000)}
window.addEventListener('arewarin-manager-loaded',load);setTimeout(init,700);
})();