
import {createClient} from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.110.8/+esm";
const sbp=window.__AREWARIN_STUDENT_SB||createClient(window.AREWARIN_CONFIG.SUPABASE_URL,window.AREWARIN_CONFIG.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const payLaunch=document.getElementById('awv9-pay-launch'),payLayer=document.getElementById('awv9-pay-layer');
const P={data:null,timer:null,user:null};
const pe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),pn=v=>Number(v||0),pmoney=v=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',minimumFractionDigits:0,maximumFractionDigits:2}).format(pn(v)),pdate=v=>v?new Intl.DateTimeFormat('th-TH',{dateStyle:'medium'}).format(new Date(v)):'-';
function ptoast(m,e=false){const x=document.createElement('div');x.className='awv9p-toast'+(e?' error':'');x.textContent=m;document.body.append(x);setTimeout(()=>x.remove(),3600)}
async function prpc(name,args={}){const{data,error}=await sbp.rpc(name,args);if(error)throw error;return data}
function tlv(id,v){return id+String(v.length).padStart(2,'0')+v}function crc16(s){let crc=0xffff;for(let i=0;i<s.length;i++){crc^=s.charCodeAt(i)<<8;for(let j=0;j<8;j++)crc=(crc&0x8000)?((crc<<1)^0x1021):(crc<<1);crc&=0xffff}return crc.toString(16).toUpperCase().padStart(4,'0')}function promptpayPayload(id,amount){let d=String(id).replace(/\D/g,''),tag='02',target=d;if(d.length===10&&d.startsWith('0')){tag='01';target='0066'+d.slice(1)}const mai=tlv('00','A000000677010111')+tlv(tag,target);let p=tlv('00','01')+tlv('01','12')+tlv('29',mai)+tlv('53','764')+tlv('54',pn(amount).toFixed(2))+tlv('58','TH')+tlv('59','AREWARIN BIOLOGY')+tlv('60','THAILAND')+'6304';return p+crc16(p)}
function insts(plan){return(P.data.installments||[]).filter(i=>i.payment_plan_id===plan.id).sort((a,b)=>pn(a.installment_no)-pn(b.installment_no))}function activeReq(inst){return(P.data.requests||[]).filter(r=>r.installment_id===inst.id&&(r.status==='slip_submitted'||(r.status==='pending'&&new Date(r.expires_at)>new Date()))).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0]}function subFor(req){return(P.data.submissions||[]).find(s=>s.payment_request_id===req?.id&&s.status==='pending')}
function pstatus(i){return({pending:'รอชำระ',partial:'ชำระบางส่วน',paid:'ชำระครบ',overdue:'เลยกำหนด',cancelled:'ยกเลิก'})[i.status]||i.status}
function renderPay(){const plans=P.data?.plans||[];payLayer.innerHTML=`<div class="awv9p-panel"><div class="awv9p-head"><div><h2>แผนแบ่งชำระและผ่อนจ่าย</h2><div style="font-size:11px;color:#d9def7">PromptPay 1901001151577 · กวดวิชาชีววิทยา อาวริน</div></div><div><button class="awv9p-btn" data-p-refresh>รีเฟรช</button> <button class="awv9p-btn danger" data-p-close>ปิด</button></div></div><div class="awv9p-body"><div class="awv9p-message">เลือกชำระเต็มงวดหรือใส่ยอดบางส่วน ระบบจะสร้าง QR ที่มีอายุ 15 นาที แล้วอัปโหลดสลิปให้แอดมินตรวจสอบ</div>${plans.length?`<div class="awv9p-grid">${plans.map(planCard).join('')}</div>`:'<div class="awv9p-empty">ยังไม่มีแผนแบ่งชำระ</div>'}${(P.data.teaching_notes||[]).length?`<div class="awv9p-card" style="margin-top:14px"><h3 style="margin-top:0">บันทึกจากผู้สอน</h3>${P.data.teaching_notes.slice(0,20).map(x=>`<div style="padding:11px;border:1px solid #e6eaf3;border-radius:13px;margin-top:8px"><b>${pe(x.topic||'บันทึกหลังเรียน')}</b><div style="font-size:10px;color:#8993a9">${pdate(x.lesson_date)}</div><div style="margin-top:6px">${pe(x.lesson_summary||'')}</div>${x.homework?`<div class="awv9p-message" style="margin-top:8px;margin-bottom:0"><b>การบ้าน:</b> ${pe(x.homework)}</div>`:''}</div>`).join('')}</div>`:''}</div></div>`;bindPay();renderPqrs();startPtimer()}
function planCard(p){const pct=p.total_amount?Math.min(100,Math.round(pn(p.amount_paid)/pn(p.total_amount)*100)):0;return `<article class="awv9p-card"><div class="awv9p-row"><div><span class="awv9p-chip ${p.status==='paid'?'green':'amber'}">${p.status==='paid'?'ชำระครบ':'กำลังผ่อน'}</span><h3 style="margin:8px 0 3px">${pe(p.title)}</h3></div><b>${pmoney(p.balance_amount)}<div style="font-size:10px;color:#8993a9">คงเหลือ</div></b></div><div class="awv9p-row" style="font-size:11px;color:#77819b"><span>ยอดรวม ${pmoney(p.total_amount)}</span><span>รับแล้ว ${pmoney(p.amount_paid)}</span></div><div class="awv9p-progress"><i style="width:${pct}%"></i></div>${insts(p).map(installmentCard).join('')}</article>`}
function installmentCard(i){const balance=Math.max(0,pn(i.amount_due)-pn(i.amount_paid)),req=activeReq(i),sub=subFor(req);return `<div class="awv9p-inst"><b>${i.installment_no}</b><div><div>งวดที่ ${i.installment_no} · ${pdate(i.due_date)}</div><div style="font-size:10px;color:#8993a9">${pmoney(i.amount_paid)} / ${pmoney(i.amount_due)}</div></div><div><span class="awv9p-chip ${i.status==='paid'?'green':i.status==='partial'?'amber':i.status==='overdue'?'red':''}">${pstatus(i)}</span></div>${balance>0&&!req?`<div style="grid-column:1/-1;display:grid;grid-template-columns:1fr auto;gap:8px"><input class="awv9p-input" type="number" step="0.01" min="0.01" max="${balance}" id="pay-amount-${i.id}" value="${balance}"><button class="awv9p-btn primary" data-create-qr="${i.id}">สร้าง QR</button></div>`:''}${req?requestCard(req,sub):''}</div>`}
function requestCard(r,sub){return `<div style="grid-column:1/-1"><div class="awv9p-qr"><canvas data-pqr="${r.id}"></canvas><div class="awv9p-count" data-pcount="${r.id}">--:--</div><b>${pmoney(r.amount)}</b><div style="font-size:10px;color:#8993a9">QR มีอายุ 15 นาที</div></div>${r.status==='pending'?`<button class="awv9p-btn success" style="width:100%;margin-top:8px" data-upload-partial="${r.id}">อัปโหลดสลิป</button>`:sub?'<div class="awv9p-message" style="margin-top:8px">ส่งสลิปแล้ว รอตรวจสอบ</div>':'<div class="awv9p-message" style="margin-top:8px">กำลังตรวจสอบรายการ</div>'}</div>`}
async function loadPay(){payLayer.classList.add('open');payLayer.innerHTML='<div class="awv9p-panel" style="display:grid;place-items:center;min-height:300px">กำลังโหลดแผนชำระ...</div>';try{P.data=await prpc('student_v9_payment_bootstrap');renderPay()}catch(e){payLayer.innerHTML=`<div class="awv9p-panel" style="padding:22px"><div class="awv9p-message">${pe(e.message)}</div><button class="awv9p-btn danger" data-p-close>ปิด</button></div>`;payLayer.querySelector('[data-p-close]').onclick=()=>payLayer.classList.remove('open')}}
function renderPqrs(){payLayer.querySelectorAll('[data-pqr]').forEach(c=>{const r=P.data.requests.find(x=>x.id===c.dataset.pqr),plan=P.data.plans.find(p=>p.id===r?.payment_plan_id);if(r&&window.QRCode)QRCode.toCanvas(c,promptpayPayload(plan?.promptpay_id||'1901001151577',r.amount),{width:210,margin:1,errorCorrectionLevel:'M'}).catch(()=>{})})}
function startPtimer(){clearInterval(P.timer);const tick=()=>payLayer.querySelectorAll('[data-pcount]').forEach(el=>{const r=P.data.requests.find(x=>x.id===el.dataset.pcount),ms=new Date(r.expires_at)-new Date();if(ms<=0){el.textContent='00:00';return}el.textContent=`${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms%60000/1000)).padStart(2,'0')}`});tick();P.timer=setInterval(tick,1000)}
function uploadPartial(id){const req=P.data.requests.find(r=>r.id===id);payLayer.insertAdjacentHTML('beforeend',`<div id="awv9-slip-modal" style="position:fixed;inset:0;z-index:100002;background:rgba(10,16,38,.68);display:grid;place-items:center;padding:18px"><div class="awv9p-card" style="width:min(520px,100%)"><h3>อัปโหลดสลิป ${pmoney(req.amount)}</h3><input class="awv9p-input" type="file" id="awv9-slip-file" accept="image/*,application/pdf"><input class="awv9p-input" style="margin-top:8px" id="awv9-slip-note" placeholder="หมายเหตุ (ถ้ามี)"><div style="display:flex;gap:8px;margin-top:10px"><button class="awv9p-btn" id="awv9-slip-cancel">ยกเลิก</button><button class="awv9p-btn primary" id="awv9-slip-send">อัปโหลดและยืนยัน</button></div></div></div>`);document.getElementById('awv9-slip-cancel').onclick=()=>document.getElementById('awv9-slip-modal').remove();document.getElementById('awv9-slip-send').onclick=async()=>{const file=document.getElementById('awv9-slip-file').files[0];if(!file)return ptoast('กรุณาเลือกไฟล์',true);const path=`${P.user.id}/${id}/${Date.now()}-${file.name.replace(/[^\w.ก-๙-]+/g,'-')}`;try{const{error}=await sbp.storage.from('portal-slips').upload(path,file,{contentType:file.type||undefined});if(error)throw error;await prpc('student_v8_submit_slip',{p_payment_request_id:id,p_storage_path:path,p_original_filename:file.name,p_amount:req.amount,p_note:document.getElementById('awv9-slip-note').value||''});document.getElementById('awv9-slip-modal').remove();ptoast('ส่งสลิปแล้ว');await loadPay()}catch(e){await sbp.storage.from('portal-slips').remove([path]);ptoast(e.message,true)}}}
function bindPay(){payLayer.querySelector('[data-p-close]').onclick=()=>payLayer.classList.remove('open');payLayer.querySelector('[data-p-refresh]').onclick=loadPay;payLayer.querySelectorAll('[data-create-qr]').forEach(b=>b.onclick=async()=>{const amount=pn(payLayer.querySelector(`#pay-amount-${b.dataset.createQr}`)?.value);try{await prpc('student_v9_create_installment_qr',{p_installment_id:b.dataset.createQr,p_amount:amount});ptoast('สร้าง QR แล้ว');await loadPay()}catch(e){ptoast(e.message,true)}});payLayer.querySelectorAll('[data-upload-partial]').forEach(b=>b.onclick=()=>uploadPartial(b.dataset.uploadPartial))}
if(payLaunch)payLaunch.style.display='none';window.__AREWARIN_OPEN_INSTALLMENTS__=loadPay;payLayer.addEventListener('click',e=>{if(e.target===payLayer)payLayer.classList.remove('open')});
async function detectPay(){try{const{data}=await sbp.auth.getSession();P.user=data.session?.user||null;if(payLaunch)payLaunch.style.display='none'}catch{if(payLaunch)payLaunch.style.display='none'}}
setInterval(detectPay,3500);detectPay();
