(() => {
  'use strict';
  const sb = window.AreWarinAPI?.sb;
  const cfg = window.AREWARIN_CONFIG || {};
  const $ = id => document.getElementById(id);
  const esc = v => String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const cleanPhone = v => String(v||'').replace(/\D/g,'');
  const DRAFT_KEY='arewarin_tutor_application_draft_v1';
  let step=1, eduSeq=0, workSeq=0;

  const days=[['mon','จันทร์'],['tue','อังคาร'],['wed','พุธ'],['thu','พฤหัสบดี'],['fri','ศุกร์'],['sat','เสาร์'],['sun','อาทิตย์']];
  const fallbackSubjects=[['bio','ชีววิทยา'],['chem','เคมี'],['sci','วิทยาศาสตร์'],['math','คณิตศาสตร์'],['other','อื่นๆ']];

  function toast(icon,title,text=''){return Swal.fire({icon,title,text,confirmButtonColor:'#0f172a',customClass:{popup:'rounded-[1.5rem]'}})}
  function formatPhoneInput(){const el=$('phone');let v=cleanPhone(el.value).slice(0,10);el.value=v.length>6?`${v.slice(0,3)}-${v.slice(3,6)}-${v.slice(6)}`:v.length>3?`${v.slice(0,3)}-${v.slice(3)}`:v;}
  function setStep(n){step=Math.max(1,Math.min(4,n));document.querySelectorAll('.step-pane').forEach(p=>p.classList.toggle('active',Number(p.dataset.step)===step));document.querySelectorAll('[data-step-indicator]').forEach(x=>{const s=Number(x.dataset.stepIndicator);x.classList.toggle('active',s===step);x.classList.toggle('done',s<step);x.querySelector('.step-dot').innerHTML=s<step?'<i class="fas fa-check"></i>':String(s)});$('btnBack').classList.toggle('invisible',step===1);$('btnNext').classList.toggle('hidden',step===4);$('btnSubmit').classList.toggle('hidden',step!==4);window.scrollTo({top:80,behavior:'smooth'});}

  function educationRow(data={}){const id=++eduSeq;const el=document.createElement('div');el.className='repeat-row';el.dataset.row='education';el.innerHTML=`<div class="flex justify-between items-center mb-2"><div class="text-[10px] font-semibold text-slate-600">รายการการศึกษา</div><button type="button" class="remove-btn" title="ลบ"><i class="fas fa-xmark"></i></button></div><div class="grid md:grid-cols-2 gap-2"><input class="field edu-institution" placeholder="สถาบัน / มหาวิทยาลัย *" value="${esc(data.institution||'')}"><input class="field edu-degree" placeholder="ระดับ / ปริญญา" value="${esc(data.degree||'')}"><input class="field edu-major" placeholder="คณะ / สาขา" value="${esc(data.major||'')}"><input class="field edu-year" placeholder="ปีที่จบ / กำลังศึกษา" value="${esc(data.year||'')}"></div><input class="field edu-detail mt-2" placeholder="รายละเอียดเพิ่มเติม (ถ้ามี)" value="${esc(data.detail||'')}">`;el.querySelector('.remove-btn').onclick=()=>{el.remove();saveDraftSoon()};el.querySelectorAll('input').forEach(i=>i.addEventListener('input',saveDraftSoon));$('educationList').appendChild(el);return el;}
  function workRow(data={}){workSeq++;const el=document.createElement('div');el.className='repeat-row';el.dataset.row='work';el.innerHTML=`<div class="flex justify-between items-center mb-2"><div class="text-[10px] font-semibold text-slate-600">รายการประสบการณ์</div><button type="button" class="remove-btn" title="ลบ"><i class="fas fa-xmark"></i></button></div><div class="grid md:grid-cols-2 gap-2"><input class="field work-org" placeholder="สถานที่ทำงาน / สถาบัน" value="${esc(data.organization||'')}"><input class="field work-role" placeholder="ตำแหน่ง / บทบาท" value="${esc(data.role||'')}"><input class="field work-period" placeholder="ช่วงเวลา เช่น 2024–ปัจจุบัน" value="${esc(data.period||'')}"><input class="field work-subject" placeholder="วิชา / งานที่เกี่ยวข้อง" value="${esc(data.subject||'')}"></div><textarea class="field work-detail mt-2" placeholder="หน้าที่หรือผลงานโดยย่อ">${esc(data.detail||'')}</textarea>`;el.querySelector('.remove-btn').onclick=()=>{el.remove();saveDraftSoon()};el.querySelectorAll('input,textarea').forEach(i=>i.addEventListener('input',saveDraftSoon));$('workList').appendChild(el);return el;}
  function renderAvailability(saved=[]){const map=Object.fromEntries((saved||[]).map(x=>[x.day,x]));$('availabilityGrid').innerHTML=days.map(([key,label])=>{const s=map[key]||{};return `<div class="day-card ${s.enabled?'on':''}" data-day="${key}"><div class="day-head"><label class="flex items-center gap-2 text-[10.5px] font-semibold text-slate-700"><input class="day-toggle" type="checkbox" ${s.enabled?'checked':''}> ${label}</label><span class="text-[8px] text-slate-400">Weekly</span></div><div class="day-times"><input class="field day-start !min-h-[38px]" type="time" value="${esc(s.start||'09:00')}"><input class="field day-end !min-h-[38px]" type="time" value="${esc(s.end||'18:00')}"></div></div>`}).join('');document.querySelectorAll('.day-card').forEach(card=>{const tog=card.querySelector('.day-toggle');tog.addEventListener('change',()=>{card.classList.toggle('on',tog.checked);saveDraftSoon()});card.querySelectorAll('input').forEach(i=>i.addEventListener('input',saveDraftSoon));});}

  async function loadBrandAndSubjects(){if(!sb)return;try{const [b,c]=await Promise.all([sb.from('site_branding').select('*').eq('id',1).maybeSingle(),sb.from('subject_categories').select('id,name_th,name_en,icon_class,active,sort_order').eq('active',true).order('sort_order')]);if(b.data){if(b.data.logo_url)$('brandLogo').src=b.data.logo_url;$('brandName').textContent=b.data.brand_name_en||'AreWarin Biology';}renderSubjects(c.data?.length?c.data.map(x=>[x.id,x.name_th||x.name_en,x.icon_class]):fallbackSubjects);}catch(e){renderSubjects(fallbackSubjects)}}
  function renderSubjects(rows){$('subjectChoices').innerHTML=rows.map(([key,label,icon])=>`<label class="choice"><input type="checkbox" name="subjects" value="${esc(key)}"><i class="${esc(icon||'fas fa-book-open')} text-sky-400"></i><span>${esc(label)}</span></label>`).join('');document.querySelectorAll('input[name="subjects"]').forEach(i=>i.addEventListener('change',saveDraftSoon));}

  function collectEducation(){return [...document.querySelectorAll('[data-row="education"]')].map(r=>({institution:r.querySelector('.edu-institution').value.trim(),degree:r.querySelector('.edu-degree').value.trim(),major:r.querySelector('.edu-major').value.trim(),year:r.querySelector('.edu-year').value.trim(),detail:r.querySelector('.edu-detail').value.trim()})).filter(x=>Object.values(x).some(Boolean));}
  function collectWork(){return [...document.querySelectorAll('[data-row="work"]')].map(r=>({organization:r.querySelector('.work-org').value.trim(),role:r.querySelector('.work-role').value.trim(),period:r.querySelector('.work-period').value.trim(),subject:r.querySelector('.work-subject').value.trim(),detail:r.querySelector('.work-detail').value.trim()})).filter(x=>Object.values(x).some(Boolean));}
  function collectAvailability(){return [...document.querySelectorAll('.day-card')].filter(c=>c.querySelector('.day-toggle').checked).map(c=>({day:c.dataset.day,enabled:true,start:c.querySelector('.day-start').value,end:c.querySelector('.day-end').value}));}
  function checked(name){return [...document.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value)}
  function payload(){return {first_name:$('firstName').value.trim(),last_name:$('lastName').value.trim(),nickname:$('nickname').value.trim(),phone:cleanPhone($('phone').value),email:$('email').value.trim().toLowerCase(),line_id:$('lineId').value.trim(),province:$('province').value.trim(),current_occupation:$('currentOccupation').value.trim(),intro:$('intro').value.trim(),education:collectEducation(),work_experience:collectWork(),achievements:$('achievements').value.trim(),subjects:checked('subjects'),levels:checked('levels'),teaching_modes:checked('modes'),teaching_experience_years:Number($('experienceYears').value||0),expected_rate:$('expectedRate').value.trim(),preferred_location:$('preferredLocation').value.trim(),availability:collectAvailability(),teaching_style:$('teachingStyle').value.trim(),why_join:$('whyJoin').value.trim(),additional_note:$('additionalNote').value.trim(),consent_pdpa:$('pdpaCheck').checked,certified_accuracy:$('accuracyCheck').checked};}

  function validateStep(n){if(n===1){for(const id of ['firstName','lastName','nickname','phone','email']){const el=$(id);if(!el.value.trim()){el.focus();toast('warning','กรอกข้อมูลให้ครบ','กรุณากรอกช่องที่มีเครื่องหมาย *');return false}}if(cleanPhone($('phone').value).length<9){$('phone').focus();toast('warning','ตรวจสอบเบอร์โทร','กรุณากรอกเบอร์โทรให้ถูกต้อง');return false}if(!$('email').checkValidity()){ $('email').focus();toast('warning','ตรวจสอบอีเมล','รูปแบบอีเมลไม่ถูกต้อง');return false}}
    if(n===2){const ed=collectEducation();if(!ed.length||!ed[0].institution){toast('warning','เพิ่มประวัติการศึกษา','กรุณาระบุสถาบันการศึกษาอย่างน้อย 1 รายการ');return false}}
    if(n===3){if(!checked('subjects').length){toast('warning','เลือกวิชาที่สอน','กรุณาเลือกอย่างน้อย 1 วิชา');return false}if(!checked('levels').length){toast('warning','เลือกระดับผู้เรียน','กรุณาเลือกอย่างน้อย 1 ระดับ');return false}if(!checked('modes').length){toast('warning','เลือกรูปแบบการสอน','กรุณาเลือก Online หรือ Onsite อย่างน้อย 1 แบบ');return false}if(!collectAvailability().length){toast('warning','เลือกวันที่สะดวก','กรุณาเลือกอย่างน้อย 1 วัน');return false}}
    if(n===4){if(!$('accuracyCheck').checked||!$('pdpaCheck').checked){toast('warning','กรุณายืนยันข้อมูล','ต้องยืนยันความถูกต้องและการใช้ข้อมูลก่อนส่งใบสมัคร');return false}}
    return true;}

  let draftTimer;function saveDraftSoon(){clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,350)}
  function saveDraft(){try{localStorage.setItem(DRAFT_KEY,JSON.stringify(payload()));$('draftStatus').innerHTML='<i class="fas fa-check text-emerald-500 mr-1"></i> บันทึกร่างแล้ว';setTimeout(()=>{$('draftStatus').innerHTML='<i class="far fa-floppy-disk mr-1"></i> บันทึกร่างอัตโนมัติ'},1300)}catch{}}
  function restoreDraft(){try{const d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(!d)return false;const map={firstName:d.first_name,lastName:d.last_name,nickname:d.nickname,phone:d.phone,email:d.email,lineId:d.line_id,province:d.province,currentOccupation:d.current_occupation,intro:d.intro,achievements:d.achievements,experienceYears:d.teaching_experience_years,expectedRate:d.expected_rate,preferredLocation:d.preferred_location,teachingStyle:d.teaching_style,whyJoin:d.why_join,additionalNote:d.additional_note};Object.entries(map).forEach(([id,v])=>{if($(id)&&v!=null)$(id).value=v});$('educationList').innerHTML='';(d.education?.length?d.education:[{}]).forEach(educationRow);$('workList').innerHTML='';(d.work_experience||[]).forEach(workRow);renderAvailability(d.availability||[]);setTimeout(()=>{(d.subjects||[]).forEach(v=>{const el=document.querySelector(`input[name="subjects"][value="${CSS.escape(v)}"]`);if(el)el.checked=true});(d.levels||[]).forEach(v=>{const el=document.querySelector(`input[name="levels"][value="${CSS.escape(v)}"]`);if(el)el.checked=true});(d.teaching_modes||[]).forEach(v=>{const el=document.querySelector(`input[name="modes"][value="${CSS.escape(v)}"]`);if(el)el.checked=true})},300);return true}catch{return false}}

  function validateFiles(){const rules=[['profilePhoto',5],['resumeFile',10],['portfolioFile',10],['transcriptFile',10]];for(const [id,max] of rules){const f=$(id).files[0];if(f&&f.size>max*1024*1024){toast('warning','ไฟล์ใหญ่เกินไป',`${f.name} ต้องไม่เกิน ${max} MB`);return false}}return true}
  async function submitApplication(){if(!sb||!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY)return toast('error','ยังไม่ได้เชื่อมระบบ','ไม่พบการตั้งค่า Supabase');if(!validateFiles())return;const fd=new FormData();fd.append('payload',JSON.stringify(payload()));[['profile_photo','profilePhoto'],['resume','resumeFile'],['portfolio','portfolioFile'],['transcript','transcriptFile']].forEach(([key,id])=>{const f=$(id).files[0];if(f)fd.append(key,f,f.name)});$('btnSubmit').disabled=true;$('btnSubmit').innerHTML='<i class="fas fa-circle-notch fa-spin"></i> กำลังส่ง...';try{const res=await fetch(`${cfg.SUPABASE_URL}/functions/v1/submit-tutor-application`,{method:'POST',headers:{apikey:cfg.SUPABASE_ANON_KEY,Authorization:`Bearer ${cfg.SUPABASE_ANON_KEY}`},body:fd});let data={};try{data=await res.json()}catch{}if(!res.ok||!data.success)throw new Error(data.message||`HTTP ${res.status}`);localStorage.removeItem(DRAFT_KEY);const no=data.application_no;await Swal.fire({icon:'success',title:'ส่งใบสมัครเรียบร้อย',html:`<div class="text-[11px] text-slate-500">เลขใบสมัครของคุณ</div><div class="mt-2 px-4 py-3 rounded-xl bg-slate-900 text-white font-mono text-lg tracking-wide">${esc(no)}</div><div class="mt-3 text-[10px] text-slate-400 leading-relaxed">กรุณาบันทึกเลขนี้ไว้ ใช้ร่วมกับเบอร์โทรเพื่อเช็คสถานะใบสมัคร</div>`,confirmButtonText:'กลับหน้าหลัก',confirmButtonColor:'#0f172a',customClass:{popup:'rounded-[1.5rem]'}});location.href='../';}catch(e){toast('error','ส่งใบสมัครไม่สำเร็จ',e.message||'กรุณาลองใหม่อีกครั้ง')}finally{$('btnSubmit').disabled=false;$('btnSubmit').innerHTML='ส่งใบสมัคร <i class="fas fa-paper-plane"></i>'}}

  const statusInfo={new:['รับใบสมัครแล้ว','bg-sky-50 text-sky-700'],reviewing:['กำลังตรวจสอบ','bg-amber-50 text-amber-700'],interview:['นัดสัมภาษณ์ / ทดลองสอน','bg-violet-50 text-violet-700'],accepted:['ผ่านการพิจารณา','bg-emerald-50 text-emerald-700'],rejected:['ไม่ผ่านการพิจารณา','bg-rose-50 text-rose-700'],withdrawn:['ยกเลิกใบสมัคร','bg-slate-100 text-slate-600']};
  async function checkStatus(){if(!sb)return toast('error','ยังไม่ได้เชื่อมระบบ');const {value}=await Swal.fire({title:'เช็คสถานะใบสมัคร',html:'<div class="text-left space-y-3"><label class="label">เลขใบสมัคร<input id="statusNo" class="field mt-1" placeholder="AWT-2026-000001"></label><label class="label">เบอร์โทร<input id="statusPhone" class="field mt-1" placeholder="08xxxxxxxx"></label></div>',showCancelButton:true,confirmButtonText:'ตรวจสอบ',cancelButtonText:'ยกเลิก',confirmButtonColor:'#0f172a',customClass:{popup:'rounded-[1.5rem]'},preConfirm:()=>{const no=document.getElementById('statusNo').value.trim(),phone=cleanPhone(document.getElementById('statusPhone').value);if(!no||phone.length<9){Swal.showValidationMessage('กรอกเลขใบสมัครและเบอร์โทร');return false}return{no,phone}}});if(!value)return;Swal.fire({title:'กำลังตรวจสอบ...',didOpen:()=>Swal.showLoading(),showConfirmButton:false,allowOutsideClick:false});const {data,error}=await sb.rpc('check_tutor_application_status',{p_application_no:value.no,p_phone:value.phone});if(error)return toast('error','ตรวจสอบไม่ได้',error.message);if(!data?.found)return toast('warning','ไม่พบใบสมัคร','กรุณาตรวจสอบเลขใบสมัครและเบอร์โทรอีกครั้ง');const [label,cls]=statusInfo[data.status]||[data.status,'bg-slate-100 text-slate-600'];Swal.fire({title:'สถานะใบสมัคร',html:`<div class="text-left"><div class="status-modal-row"><span>เลขใบสมัคร</span><b class="font-mono">${esc(data.application_no)}</b></div><div class="status-modal-row"><span>ผู้สมัคร</span><b>${esc(data.applicant_name)}</b></div><div class="status-modal-row"><span>วันที่ส่ง</span><span>${new Date(data.created_at).toLocaleDateString('th-TH')}</span></div><div class="status-modal-row"><span>สถานะ</span><span><span class="status-pill ${cls}">${esc(label)}</span></span></div>${data.public_status_note?`<div class="mt-3 p-3 rounded-xl bg-slate-50 border border-slate-100 text-[10px] text-slate-600 leading-relaxed">${esc(data.public_status_note)}</div>`:''}</div>`,confirmButtonText:'ปิด',confirmButtonColor:'#0f172a',customClass:{popup:'rounded-[1.5rem]'}})}

  $('year').textContent=new Date().getFullYear();$('phone').addEventListener('input',()=>{formatPhoneInput();saveDraftSoon()});$('addEducation').onclick=()=>educationRow();$('addWork').onclick=()=>workRow();$('btnNext').onclick=()=>{if(validateStep(step))setStep(step+1)};$('btnBack').onclick=()=>setStep(step-1);$('applicationForm').onsubmit=e=>{e.preventDefault();if(validateStep(4))submitApplication()};$('btnCheckStatus').onclick=checkStatus;$('btnCheckStatusMobile').onclick=checkStatus;
  document.querySelectorAll('#applicationForm input,#applicationForm textarea,#applicationForm select').forEach(el=>{if(!['file','checkbox'].includes(el.type))el.addEventListener('input',saveDraftSoon);if(el.type==='checkbox')el.addEventListener('change',saveDraftSoon)});
  educationRow();renderAvailability([]);loadBrandAndSubjects().then(()=>restoreDraft());
})();
