import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const corsHeaders={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, accept','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Max-Age':'86400'};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,'Content-Type':'application/json; charset=utf-8'}});
const clean=v=>String(v??'').trim();const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const errText=e=>e?.message||e?.details||String(e||'Unknown error');
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders});
 if(req.method==='GET')return json({ok:true,function:'create-group-class-enrollment',version:'v24'});
 if(req.method!=='POST')return json({success:false,message:'Method not allowed'},405);
 const url=Deno.env.get('SUPABASE_URL'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!service)return json({success:false,message:'Supabase environment incomplete'},500);
 const sb=createClient(url,service,{auth:{persistSession:false}});let enrollmentId=null,slipPath=null,reservationId=null;
 try{
   const d=await req.json();const groupId=clean(d.groupClassId);const fullname=clean(d.fullname),phone=clean(d.phone);if(!groupId)throw new Error('ไม่พบคลาสกลุ่มที่เลือก');if(!fullname)throw new Error('กรุณากรอกชื่อผู้สมัคร');if(phone.replace(/\D/g,'').length<9)throw new Error('กรุณาตรวจสอบเบอร์โทร');if(!d.groupPolicyAccepted)throw new Error('กรุณายอมรับเงื่อนไขของคลาสกลุ่ม');
   const {data:g,error:gErr}=await sb.from('os_student_groups').select('id,group_code,name,course_id,tutor_id,price_amount,included_hours,included_sessions,mode,location,enrollment_open,public_visible,status,allow_promotions,absence_deduct_hours,recording_on_absence').eq('id',groupId).maybeSingle();if(gErr||!g)throw new Error('ไม่พบคลาสกลุ่ม');
   const {data:course}=await sb.from('courses').select('id,name').eq('id',g.course_id).maybeSingle();const {data:tutor}=await sb.from('tutors').select('id,display_name').eq('id',g.tutor_id).maybeSingle();
   const hold=await sb.rpc('group_class_create_hold',{p_group_id:g.id,p_phone:phone,p_fullname:fullname,p_seats:1});if(hold.error)throw hold.error;reservationId=hold.data?.reservation_id;if(!reservationId)throw new Error('จองที่นั่งไม่สำเร็จ');
   let finalAmount=Math.max(0,num(g.price_amount));let promoCode=clean(d.discountCode).toUpperCase()||null;
   if(g.allow_promotions&&promoCode){const {data:p}=await sb.from('promotions').select('*').eq('code',promoCode).eq('active',true).maybeSingle();if(p){const now=Date.now();if((!p.starts_at||now>=new Date(p.starts_at).getTime())&&(!p.ends_at||now<=new Date(p.ends_at).getTime())){const v=num(p.discount_value);finalAmount=Math.max(0,finalAmount-(p.discount_type==='percent'?Math.round(finalAmount*v/100):v));}else promoCode=null}else promoCode=null}else promoCode=null;
   const {data:schedules}=await sb.from('os_student_group_schedules').select('weekday,start_time,end_time').eq('group_id',g.id).eq('active',true).order('weekday').order('start_time');const days={1:'จันทร์',2:'อังคาร',3:'พุธ',4:'พฤหัสบดี',5:'ศุกร์',6:'เสาร์',7:'อาทิตย์'};const timeText=(schedules||[]).map(x=>`${days[x.weekday]||''} ${String(x.start_time).slice(0,5)}–${String(x.end_time).slice(0,5)}`).join(', ');
   let receiptNo=null;const rr=await sb.rpc('next_receipt_no');if(!rr.error)receiptNo=rr.data||null;
   const studentType=clean(d.studentType)==='old'?'old':'new';
   const row={receipt_no:receiptNo,student_type:studentType,fullname,nickname:clean(d.nickname)||null,phone,line_id:clean(d.lineId)||null,email:clean(d.email)||null,grade:clean(d.grade)||null,school:clean(d.school)||null,faculty:clean(d.faculty)||null,province:clean(d.province)||null,parent_name:clean(d.parentName)||null,parent_relation:clean(d.parentRelation)||null,parent_phone:clean(d.parentPhone)||null,study_type:'group',group_size:1,additional_students:[],tutor_text:tutor?.display_name||clean(d.tutor)||null,course_text:course?.name||clean(d.course)||null,mode_text:`Group Class · ${g.name}`,hours_text:g.included_hours!=null?String(g.included_hours):null,time_text:timeText+(g.location?` · ${g.location}`:''),amount_quoted:finalAmount,promotion_code:promoCode,status:'pending_payment_verification',policy_version_acknowledged:Math.max(1,Math.floor(num(d.policyVersion,1))),policy_acknowledged_at:new Date().toISOString(),raw_payload:{...d,fileData:undefined,groupClassId:g.id,groupClassCode:g.group_code,serverGroupPrice:g.price_amount,absenceDeductHours:g.absence_deduct_hours,recordingOnAbsence:g.recording_on_absence}};
   let er=await sb.from('enrollments').insert(row).select('id,receipt_no,receipt_token').single();if(er.error){const fallback={...row};delete fallback.policy_version_acknowledged;delete fallback.policy_acknowledged_at;er=await sb.from('enrollments').insert(fallback).select('id,receipt_no,receipt_token').single()}if(er.error||!er.data)throw new Error('บันทึกใบสมัครไม่ได้: '+errText(er.error));enrollmentId=er.data.id;
   const item={enrollment_id:enrollmentId,course_id:g.course_id,tutor_id:g.tutor_id,offering_id:d.courseItems?.[0]?.offeringId||null,course_name_snapshot:course?.name||clean(d.course),tutor_name_snapshot:tutor?.display_name||clean(d.tutor)||null,package_code:'group_class',share_mode:'shared',hours_allocated:g.included_hours??0,hours_unlimited:false,amount_allocated:finalAmount,status:'pending'};const ir=await sb.from('enrollment_items').insert(item);if(ir.error)throw new Error('บันทึกคอร์สกลุ่มไม่ได้: '+errText(ir.error));
   const attach=await sb.rpc('group_class_attach_hold',{p_reservation_id:reservationId,p_enrollment_id:enrollmentId});if(attach.error)throw attach.error;
   const method=clean(d.paymentMethod)==='cash'?'cash':'transfer';if(method==='transfer'){if(!d.fileData)throw new Error('กรุณาแนบสลิปการชำระเงิน');const binary=Uint8Array.from(atob(String(d.fileData)),c=>c.charCodeAt(0));const raw=clean(d.fileName)||'slip.jpg',ext=(raw.split('.').pop()||'jpg').replace(/[^a-zA-Z0-9]/g,'').toLowerCase()||'jpg';slipPath=`${new Date().toISOString().slice(0,7)}/${enrollmentId}.${ext}`;const up=await sb.storage.from('payment-slips').upload(slipPath,binary,{contentType:clean(d.mimeType)||'image/jpeg',upsert:false});if(up.error)throw new Error('อัปโหลดสลิปไม่สำเร็จ: '+errText(up.error))}
   const pay=await sb.from('payments').insert({enrollment_id:enrollmentId,payment_method:method,amount_submitted:finalAmount,slip_path:slipPath,status:'pending'});if(pay.error)throw new Error('บันทึกการชำระเงินไม่สำเร็จ: '+errText(pay.error));
   return json({success:true,enrollmentId,receiptNo:er.data.receipt_no||receiptNo,receiptToken:er.data.receipt_token,amount:finalAmount,status:'pending',groupClassId:g.id,groupClassCode:g.group_code,reservationId,version:'v24-group-class'});
 }catch(e){console.error('create-group-class-enrollment',e);if(enrollmentId)await sb.from('enrollments').delete().eq('id',enrollmentId);if(slipPath)await sb.storage.from('payment-slips').remove([slipPath]);if(reservationId)await sb.rpc('group_class_cancel_hold',{p_reservation_id:reservationId});return json({success:false,message:errText(e),version:'v24-group-class'},400)}
});
